// Code generated by protoc-gen-go. DO NOT EDIT.
// source: misc.proto

package budao

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ReportVideoRequest struct {
	Header  *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	VideoId string  `protobuf:"bytes,2,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	Reason  string  `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
}

func (m *ReportVideoRequest) Reset()                    { *m = ReportVideoRequest{} }
func (m *ReportVideoRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportVideoRequest) ProtoMessage()               {}
func (*ReportVideoRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *ReportVideoRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReportVideoRequest) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *ReportVideoRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ReportVideoResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ReportVideoResponse) Reset()                    { *m = ReportVideoResponse{} }
func (m *ReportVideoResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportVideoResponse) ProtoMessage()               {}
func (*ReportVideoResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *ReportVideoResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReportCommentRequest struct {
	Header    *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	CommentId string  `protobuf:"bytes,2,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
	Reason    string  `protobuf:"bytes,3,opt,name=reason" json:"reason,omitempty"`
}

func (m *ReportCommentRequest) Reset()                    { *m = ReportCommentRequest{} }
func (m *ReportCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*ReportCommentRequest) ProtoMessage()               {}
func (*ReportCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *ReportCommentRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ReportCommentRequest) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *ReportCommentRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ReportCommentResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ReportCommentResponse) Reset()                    { *m = ReportCommentResponse{} }
func (m *ReportCommentResponse) String() string            { return proto.CompactTextString(m) }
func (*ReportCommentResponse) ProtoMessage()               {}
func (*ReportCommentResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *ReportCommentResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type UserFeedbackRequest struct {
	Header   *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Feedback string  `protobuf:"bytes,2,opt,name=feedback" json:"feedback,omitempty"`
	Contact  string  `protobuf:"bytes,3,opt,name=contact" json:"contact,omitempty"`
}

func (m *UserFeedbackRequest) Reset()                    { *m = UserFeedbackRequest{} }
func (m *UserFeedbackRequest) String() string            { return proto.CompactTextString(m) }
func (*UserFeedbackRequest) ProtoMessage()               {}
func (*UserFeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *UserFeedbackRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *UserFeedbackRequest) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

func (m *UserFeedbackRequest) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

type UserFeedbackResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *UserFeedbackResponse) Reset()                    { *m = UserFeedbackResponse{} }
func (m *UserFeedbackResponse) String() string            { return proto.CompactTextString(m) }
func (*UserFeedbackResponse) ProtoMessage()               {}
func (*UserFeedbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *UserFeedbackResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type PostDeviceTokenRequest struct {
	Header      *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	DeviceToken string  `protobuf:"bytes,2,opt,name=device_token,json=deviceToken" json:"device_token,omitempty"`
}

func (m *PostDeviceTokenRequest) Reset()                    { *m = PostDeviceTokenRequest{} }
func (m *PostDeviceTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*PostDeviceTokenRequest) ProtoMessage()               {}
func (*PostDeviceTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *PostDeviceTokenRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *PostDeviceTokenRequest) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

type PostDeviceTokenResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *PostDeviceTokenResponse) Reset()                    { *m = PostDeviceTokenResponse{} }
func (m *PostDeviceTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*PostDeviceTokenResponse) ProtoMessage()               {}
func (*PostDeviceTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *PostDeviceTokenResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetRemoteConfigRequest struct {
	Header        *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	SubmoduleHash string  `protobuf:"bytes,2,opt,name=submodule_hash,json=submoduleHash" json:"submodule_hash,omitempty"`
}

func (m *GetRemoteConfigRequest) Reset()                    { *m = GetRemoteConfigRequest{} }
func (m *GetRemoteConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRemoteConfigRequest) ProtoMessage()               {}
func (*GetRemoteConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *GetRemoteConfigRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetRemoteConfigRequest) GetSubmoduleHash() string {
	if m != nil {
		return m.SubmoduleHash
	}
	return ""
}

type GetRemoteConfigResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *GetRemoteConfigResponse) Reset()                    { *m = GetRemoteConfigResponse{} }
func (m *GetRemoteConfigResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRemoteConfigResponse) ProtoMessage()               {}
func (*GetRemoteConfigResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *GetRemoteConfigResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetVideoInfoRequest struct {
	Header  *Header `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	VideoId string  `protobuf:"bytes,2,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
}

func (m *GetVideoInfoRequest) Reset()                    { *m = GetVideoInfoRequest{} }
func (m *GetVideoInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVideoInfoRequest) ProtoMessage()               {}
func (*GetVideoInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{10} }

func (m *GetVideoInfoRequest) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetVideoInfoRequest) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

type GetVideoInfoResponse struct {
	Status   *Status   `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	ListItem *ListItem `protobuf:"bytes,2,opt,name=list_item,json=listItem" json:"list_item,omitempty"`
}

func (m *GetVideoInfoResponse) Reset()                    { *m = GetVideoInfoResponse{} }
func (m *GetVideoInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVideoInfoResponse) ProtoMessage()               {}
func (*GetVideoInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *GetVideoInfoResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetVideoInfoResponse) GetListItem() *ListItem {
	if m != nil {
		return m.ListItem
	}
	return nil
}

type ReloadConfRequest struct {
	ConfPath string `protobuf:"bytes,1,opt,name=conf_path,json=confPath" json:"conf_path,omitempty"`
}

func (m *ReloadConfRequest) Reset()                    { *m = ReloadConfRequest{} }
func (m *ReloadConfRequest) String() string            { return proto.CompactTextString(m) }
func (*ReloadConfRequest) ProtoMessage()               {}
func (*ReloadConfRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

func (m *ReloadConfRequest) GetConfPath() string {
	if m != nil {
		return m.ConfPath
	}
	return ""
}

type ReloadConfResponse struct {
	Status *Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ReloadConfResponse) Reset()                    { *m = ReloadConfResponse{} }
func (m *ReloadConfResponse) String() string            { return proto.CompactTextString(m) }
func (*ReloadConfResponse) ProtoMessage()               {}
func (*ReloadConfResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{13} }

func (m *ReloadConfResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*ReportVideoRequest)(nil), "budao.ReportVideoRequest")
	proto.RegisterType((*ReportVideoResponse)(nil), "budao.ReportVideoResponse")
	proto.RegisterType((*ReportCommentRequest)(nil), "budao.ReportCommentRequest")
	proto.RegisterType((*ReportCommentResponse)(nil), "budao.ReportCommentResponse")
	proto.RegisterType((*UserFeedbackRequest)(nil), "budao.UserFeedbackRequest")
	proto.RegisterType((*UserFeedbackResponse)(nil), "budao.UserFeedbackResponse")
	proto.RegisterType((*PostDeviceTokenRequest)(nil), "budao.PostDeviceTokenRequest")
	proto.RegisterType((*PostDeviceTokenResponse)(nil), "budao.PostDeviceTokenResponse")
	proto.RegisterType((*GetRemoteConfigRequest)(nil), "budao.GetRemoteConfigRequest")
	proto.RegisterType((*GetRemoteConfigResponse)(nil), "budao.GetRemoteConfigResponse")
	proto.RegisterType((*GetVideoInfoRequest)(nil), "budao.GetVideoInfoRequest")
	proto.RegisterType((*GetVideoInfoResponse)(nil), "budao.GetVideoInfoResponse")
	proto.RegisterType((*ReloadConfRequest)(nil), "budao.ReloadConfRequest")
	proto.RegisterType((*ReloadConfResponse)(nil), "budao.ReloadConfResponse")
}

func init() { proto.RegisterFile("misc.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x8f, 0xd2, 0x4c,
	0x14, 0x0e, 0xbb, 0xef, 0xcb, 0xc2, 0x01, 0x5c, 0x1d, 0x10, 0xa1, 0xb8, 0x66, 0x6d, 0xb2, 0xc9,
	0x5e, 0x18, 0x62, 0xf0, 0xd2, 0x8f, 0xa8, 0xbb, 0x91, 0x65, 0xa3, 0x09, 0xe9, 0xfa, 0x15, 0x6f,
	0xc8, 0xb4, 0x3d, 0xd8, 0x0a, 0x33, 0x83, 0x9d, 0x61, 0x63, 0xfc, 0x25, 0x5e, 0xfb, 0x4b, 0x4d,
	0xdb, 0xa1, 0x50, 0xe8, 0x9a, 0x4c, 0xe2, 0x1d, 0x73, 0xce, 0x3c, 0x1f, 0xd3, 0x3c, 0xe7, 0x00,
	0xc0, 0x42, 0xe9, 0xf5, 0x17, 0x91, 0x50, 0x82, 0xfc, 0xef, 0x2e, 0x7d, 0x2a, 0xac, 0xba, 0x27,
	0x18, 0x13, 0x3c, 0x2d, 0xda, 0x1c, 0x88, 0x83, 0x0b, 0x11, 0xa9, 0x8f, 0xa1, 0x8f, 0xc2, 0xc1,
	0xef, 0x4b, 0x94, 0x8a, 0x9c, 0x40, 0x39, 0x40, 0xea, 0x63, 0xd4, 0x29, 0x1d, 0x97, 0x4e, 0x6b,
	0x83, 0x46, 0x3f, 0xc1, 0xf6, 0x2f, 0x92, 0xa2, 0xa3, 0x9b, 0xa4, 0x0b, 0x95, 0xeb, 0x18, 0x36,
	0x09, 0xfd, 0xce, 0xde, 0x71, 0xe9, 0xb4, 0xea, 0x1c, 0x24, 0xe7, 0x91, 0x4f, 0xda, 0x50, 0x8e,
	0x90, 0x4a, 0xc1, 0x3b, 0xfb, 0x49, 0x43, 0x9f, 0xec, 0x67, 0xd0, 0xcc, 0xe9, 0xc9, 0x85, 0xe0,
	0x12, 0x63, 0x41, 0xa9, 0xa8, 0x5a, 0xca, 0x2d, 0xc1, 0xab, 0xa4, 0xe8, 0xe8, 0xa6, 0xad, 0xa0,
	0x95, 0xa2, 0xcf, 0x04, 0x63, 0xc8, 0x95, 0xa1, 0xdf, 0x23, 0x00, 0x2f, 0x05, 0xae, 0x1d, 0x57,
	0x75, 0xe5, 0x2f, 0x9e, 0x5f, 0xc0, 0xdd, 0x2d, 0x55, 0x33, 0xd7, 0x11, 0x34, 0x3f, 0x48, 0x8c,
	0xde, 0x20, 0xfa, 0x2e, 0xf5, 0x66, 0x86, 0xa6, 0x2d, 0xa8, 0x4c, 0x35, 0x52, 0x5b, 0xce, 0xce,
	0xa4, 0x03, 0x07, 0x9e, 0xe0, 0x8a, 0x7a, 0x4a, 0x5b, 0x5e, 0x1d, 0xed, 0xe7, 0xd0, 0xca, 0x6b,
	0x9a, 0x59, 0x76, 0xa1, 0x3d, 0x16, 0x52, 0x9d, 0xe3, 0x75, 0xe8, 0xe1, 0x7b, 0x31, 0x43, 0x6e,
	0xe8, 0xfa, 0x21, 0xd4, 0xfd, 0x04, 0x3c, 0x51, 0x31, 0x5a, 0x3b, 0xaf, 0xf9, 0x6b, 0x42, 0xfb,
	0x25, 0xdc, 0xdb, 0xd1, 0x30, 0x73, 0x39, 0x85, 0xf6, 0x10, 0x95, 0x83, 0x4c, 0x28, 0x3c, 0x13,
	0x7c, 0x1a, 0x7e, 0x35, 0x74, 0x79, 0x02, 0xb7, 0xe4, 0xd2, 0x65, 0xc2, 0x5f, 0xce, 0x71, 0x12,
	0x50, 0x19, 0x68, 0x9f, 0x8d, 0xac, 0x7a, 0x41, 0x65, 0x10, 0x3b, 0xdd, 0xd1, 0x31, 0x73, 0xfa,
	0x09, 0x9a, 0x43, 0x4c, 0x33, 0x3f, 0xe2, 0xd3, 0x7f, 0x37, 0x67, 0xf6, 0x0c, 0x5a, 0x79, 0x62,
	0x23, 0x5f, 0xe4, 0x11, 0x54, 0xe7, 0xa1, 0x54, 0x93, 0x50, 0x21, 0x4b, 0xa8, 0x6b, 0x83, 0x43,
	0x7d, 0xf3, 0x6d, 0x28, 0xd5, 0x48, 0x21, 0x73, 0x2a, 0x73, 0xfd, 0xcb, 0x7e, 0x0c, 0x77, 0x1c,
	0x9c, 0x0b, 0xea, 0xc7, 0x1f, 0x61, 0xf5, 0x86, 0x1e, 0x54, 0x3d, 0xc1, 0xa7, 0x93, 0x05, 0x55,
	0x41, 0x22, 0x56, 0x75, 0x2a, 0x71, 0x61, 0x4c, 0x55, 0x60, 0x3f, 0x8d, 0xd7, 0xcb, 0x1a, 0x61,
	0x64, 0x6e, 0xf0, 0xeb, 0x3f, 0xa8, 0xbd, 0x0b, 0xa5, 0x77, 0x85, 0x51, 0x1c, 0x11, 0x72, 0x0e,
	0xb5, 0x8d, 0xdd, 0x41, 0xba, 0x1a, 0xb5, 0xbb, 0xbf, 0x2c, 0xab, 0xa8, 0xa5, 0xc5, 0x2f, 0xa1,
	0x91, 0x9b, 0x66, 0xd2, 0xcb, 0x5d, 0xce, 0x6f, 0x16, 0xeb, 0x7e, 0x71, 0x53, 0x73, 0x0d, 0xa1,
	0xbe, 0x39, 0x65, 0x64, 0xa5, 0x5b, 0x30, 0xee, 0x56, 0xaf, 0xb0, 0xa7, 0x89, 0xc6, 0x70, 0xb8,
	0x35, 0x0b, 0xe4, 0x48, 0xdf, 0x2f, 0x9e, 0x43, 0xeb, 0xc1, 0x4d, 0xed, 0x35, 0xe3, 0x56, 0x66,
	0x33, 0xc6, 0xe2, 0x99, 0xc9, 0x18, 0x6f, 0x8a, 0xfa, 0x10, 0xea, 0x9b, 0x51, 0xcb, 0x1e, 0x5b,
	0x10, 0xec, 0xec, 0xb1, 0x85, 0xd9, 0x7c, 0x05, 0xb0, 0x0e, 0x05, 0xe9, 0x64, 0x5f, 0x78, 0x2b,
	0x59, 0x56, 0xb7, 0xa0, 0x93, 0x52, 0xbc, 0xb6, 0xe0, 0xb6, 0x27, 0x58, 0xff, 0xdb, 0x8f, 0x9f,
	0xfd, 0x85, 0x9b, 0x5e, 0x1b, 0x97, 0x7e, 0xef, 0xed, 0x5f, 0x7e, 0xfe, 0xe2, 0x96, 0x93, 0x7f,
	0xb6, 0x27, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xc7, 0xf8, 0xba, 0xfc, 0x06, 0x00, 0x00,
}
