// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transfer.proto

package budao

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 视频来源
type EVideoSource int32

const (
	EVideoSource_E_VideoSource_CRAWL_XIGUA        EVideoSource = 0
	EVideoSource_E_VideoSource_CRAWL_DOUYIN       EVideoSource = 1
	EVideoSource_E_VideoSource_CRAWL_KUAISHOU     EVideoSource = 2
	EVideoSource_E_VideoSource_CRAWL_NEIHANDUANZI EVideoSource = 3
	EVideoSource_E_VideoSource_CRAWL_JIKE         EVideoSource = 4
	EVideoSource_E_VideoSource_CRAWL_HAOKAN       EVideoSource = 5
	EVideoSource_E_VideoSource_CRAWL_BOBO         EVideoSource = 6
	EVideoSource_E_VideoSource_CRAWL_MIAOPAI      EVideoSource = 7
	EVideoSource_E_VideoSource_CRAWL_MEIPAI       EVideoSource = 8
	EVideoSource_E_VideoSource_CRAWL_BZHAN        EVideoSource = 9
	EVideoSource_E_VideoSource_CRAWL_WEIBO        EVideoSource = 10
	EVideoSource_E_VideoSource_CRAWL_LI           EVideoSource = 11
	EVideoSource_E_VideoSource_CRAWL_FEIDIESHUO   EVideoSource = 12
	EVideoSource_E_VideoSource_CRAWL_YANGGUANG    EVideoSource = 14
	EVideoSource_E_VideoSource_OWN_OPS            EVideoSource = 99
	EVideoSource_E_VideoSource_OWN_CDN            EVideoSource = 100
	EVideoSource_E_VideoSource_OWN_TEST           EVideoSource = 101
)

var EVideoSource_name = map[int32]string{
	0:   "E_VideoSource_CRAWL_XIGUA",
	1:   "E_VideoSource_CRAWL_DOUYIN",
	2:   "E_VideoSource_CRAWL_KUAISHOU",
	3:   "E_VideoSource_CRAWL_NEIHANDUANZI",
	4:   "E_VideoSource_CRAWL_JIKE",
	5:   "E_VideoSource_CRAWL_HAOKAN",
	6:   "E_VideoSource_CRAWL_BOBO",
	7:   "E_VideoSource_CRAWL_MIAOPAI",
	8:   "E_VideoSource_CRAWL_MEIPAI",
	9:   "E_VideoSource_CRAWL_BZHAN",
	10:  "E_VideoSource_CRAWL_WEIBO",
	11:  "E_VideoSource_CRAWL_LI",
	12:  "E_VideoSource_CRAWL_FEIDIESHUO",
	14:  "E_VideoSource_CRAWL_YANGGUANG",
	99:  "E_VideoSource_OWN_OPS",
	100: "E_VideoSource_OWN_CDN",
	101: "E_VideoSource_OWN_TEST",
}
var EVideoSource_value = map[string]int32{
	"E_VideoSource_CRAWL_XIGUA":        0,
	"E_VideoSource_CRAWL_DOUYIN":       1,
	"E_VideoSource_CRAWL_KUAISHOU":     2,
	"E_VideoSource_CRAWL_NEIHANDUANZI": 3,
	"E_VideoSource_CRAWL_JIKE":         4,
	"E_VideoSource_CRAWL_HAOKAN":       5,
	"E_VideoSource_CRAWL_BOBO":         6,
	"E_VideoSource_CRAWL_MIAOPAI":      7,
	"E_VideoSource_CRAWL_MEIPAI":       8,
	"E_VideoSource_CRAWL_BZHAN":        9,
	"E_VideoSource_CRAWL_WEIBO":        10,
	"E_VideoSource_CRAWL_LI":           11,
	"E_VideoSource_CRAWL_FEIDIESHUO":   12,
	"E_VideoSource_CRAWL_YANGGUANG":    14,
	"E_VideoSource_OWN_OPS":            99,
	"E_VideoSource_OWN_CDN":            100,
	"E_VideoSource_OWN_TEST":           101,
}

func (x EVideoSource) String() string {
	return proto.EnumName(EVideoSource_name, int32(x))
}
func (EVideoSource) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

type EPostResult int32

const (
	EPostResult_E_PostResult_OK           EPostResult = 0
	EPostResult_E_PostResult_Server_Error EPostResult = 1
	EPostResult_E_PostResult_Params_Error EPostResult = 2
	EPostResult_E_PostResult_Repeated     EPostResult = 3
)

var EPostResult_name = map[int32]string{
	0: "E_PostResult_OK",
	1: "E_PostResult_Server_Error",
	2: "E_PostResult_Params_Error",
	3: "E_PostResult_Repeated",
}
var EPostResult_value = map[string]int32{
	"E_PostResult_OK":           0,
	"E_PostResult_Server_Error": 1,
	"E_PostResult_Params_Error": 2,
	"E_PostResult_Repeated":     3,
}

func (x EPostResult) String() string {
	return proto.EnumName(EPostResult_name, int32(x))
}
func (EPostResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

type EAuditResult int32

const (
	EAuditResult_E_AuditResult_Pass   EAuditResult = 0
	EAuditResult_E_AuditResult_Unpass EAuditResult = 1
)

var EAuditResult_name = map[int32]string{
	0: "E_AuditResult_Pass",
	1: "E_AuditResult_Unpass",
}
var EAuditResult_value = map[string]int32{
	"E_AuditResult_Pass":   0,
	"E_AuditResult_Unpass": 1,
}

func (x EAuditResult) String() string {
	return proto.EnumName(EAuditResult_name, int32(x))
}
func (EAuditResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

// 视频信息
type PostVideo struct {
	SourceVid       string         `protobuf:"bytes,1,opt,name=source_vid,json=sourceVid" json:"source_vid,omitempty"`
	VsourceVid      string         `protobuf:"bytes,2,opt,name=vsource_vid,json=vsourceVid" json:"vsource_vid,omitempty"`
	Pic             string         `protobuf:"bytes,3,opt,name=pic" json:"pic,omitempty"`
	VideoUrl        string         `protobuf:"bytes,4,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	Title           string         `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Width           uint32         `protobuf:"varint,6,opt,name=width" json:"width,omitempty"`
	Height          uint32         `protobuf:"varint,7,opt,name=height" json:"height,omitempty"`
	Duration        uint32         `protobuf:"varint,8,opt,name=duration" json:"duration,omitempty"`
	EVideoSource    EVideoSource   `protobuf:"varint,9,opt,name=eVideoSource,enum=budao.EVideoSource" json:"eVideoSource,omitempty"`
	EVideoParseRule VideoParseRule `protobuf:"varint,10,opt,name=eVideoParseRule,enum=budao.VideoParseRule" json:"eVideoParseRule,omitempty"`
}

func (m *PostVideo) Reset()                    { *m = PostVideo{} }
func (m *PostVideo) String() string            { return proto.CompactTextString(m) }
func (*PostVideo) ProtoMessage()               {}
func (*PostVideo) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *PostVideo) GetSourceVid() string {
	if m != nil {
		return m.SourceVid
	}
	return ""
}

func (m *PostVideo) GetVsourceVid() string {
	if m != nil {
		return m.VsourceVid
	}
	return ""
}

func (m *PostVideo) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *PostVideo) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *PostVideo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostVideo) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *PostVideo) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PostVideo) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *PostVideo) GetEVideoSource() EVideoSource {
	if m != nil {
		return m.EVideoSource
	}
	return EVideoSource_E_VideoSource_CRAWL_XIGUA
}

func (m *PostVideo) GetEVideoParseRule() VideoParseRule {
	if m != nil {
		return m.EVideoParseRule
	}
	return VideoParseRule_PARSE_RULE_XIGUA
}

// 视频推送结果
type PostVideoResult struct {
	Vid             string         `protobuf:"bytes,1,opt,name=vid" json:"vid,omitempty"`
	SourceVid       string         `protobuf:"bytes,2,opt,name=source_vid,json=sourceVid" json:"source_vid,omitempty"`
	EVideoSource    EVideoSource   `protobuf:"varint,3,opt,name=eVideoSource,enum=budao.EVideoSource" json:"eVideoSource,omitempty"`
	EVideoParseRule VideoParseRule `protobuf:"varint,4,opt,name=eVideoParseRule,enum=budao.VideoParseRule" json:"eVideoParseRule,omitempty"`
	Result          EPostResult    `protobuf:"varint,5,opt,name=result,enum=budao.EPostResult" json:"result,omitempty"`
}

func (m *PostVideoResult) Reset()                    { *m = PostVideoResult{} }
func (m *PostVideoResult) String() string            { return proto.CompactTextString(m) }
func (*PostVideoResult) ProtoMessage()               {}
func (*PostVideoResult) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *PostVideoResult) GetVid() string {
	if m != nil {
		return m.Vid
	}
	return ""
}

func (m *PostVideoResult) GetSourceVid() string {
	if m != nil {
		return m.SourceVid
	}
	return ""
}

func (m *PostVideoResult) GetEVideoSource() EVideoSource {
	if m != nil {
		return m.EVideoSource
	}
	return EVideoSource_E_VideoSource_CRAWL_XIGUA
}

func (m *PostVideoResult) GetEVideoParseRule() VideoParseRule {
	if m != nil {
		return m.EVideoParseRule
	}
	return VideoParseRule_PARSE_RULE_XIGUA
}

func (m *PostVideoResult) GetResult() EPostResult {
	if m != nil {
		return m.Result
	}
	return EPostResult_E_PostResult_OK
}

// 视频推送请求
type PostVideosRequest struct {
	TVideos []*PostVideo `protobuf:"bytes,1,rep,name=tVideos" json:"tVideos,omitempty"`
}

func (m *PostVideosRequest) Reset()                    { *m = PostVideosRequest{} }
func (m *PostVideosRequest) String() string            { return proto.CompactTextString(m) }
func (*PostVideosRequest) ProtoMessage()               {}
func (*PostVideosRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *PostVideosRequest) GetTVideos() []*PostVideo {
	if m != nil {
		return m.TVideos
	}
	return nil
}

// 视频推送响应
type PostVideosResponse struct {
	TResults []*PostVideoResult `protobuf:"bytes,1,rep,name=tResults" json:"tResults,omitempty"`
}

func (m *PostVideosResponse) Reset()                    { *m = PostVideosResponse{} }
func (m *PostVideosResponse) String() string            { return proto.CompactTextString(m) }
func (*PostVideosResponse) ProtoMessage()               {}
func (*PostVideosResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *PostVideosResponse) GetTResults() []*PostVideoResult {
	if m != nil {
		return m.TResults
	}
	return nil
}

// ---------------------------------------------------
// 审核文本请求
type AuditContentRequest struct {
	ContentId   uint64 `protobuf:"varint,1,opt,name=content_id,json=contentId" json:"content_id,omitempty"`
	Content     string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
}

func (m *AuditContentRequest) Reset()                    { *m = AuditContentRequest{} }
func (m *AuditContentRequest) String() string            { return proto.CompactTextString(m) }
func (*AuditContentRequest) ProtoMessage()               {}
func (*AuditContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *AuditContentRequest) GetContentId() uint64 {
	if m != nil {
		return m.ContentId
	}
	return 0
}

func (m *AuditContentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AuditContentRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

// 审核文本响应
type AuditContentResponse struct {
	ContentId   uint64       `protobuf:"varint,1,opt,name=content_id,json=contentId" json:"content_id,omitempty"`
	Result      EPostResult  `protobuf:"varint,2,opt,name=result,enum=budao.EPostResult" json:"result,omitempty"`
	AuditResult EAuditResult `protobuf:"varint,3,opt,name=audit_result,json=auditResult,enum=budao.EAuditResult" json:"audit_result,omitempty"`
}

func (m *AuditContentResponse) Reset()                    { *m = AuditContentResponse{} }
func (m *AuditContentResponse) String() string            { return proto.CompactTextString(m) }
func (*AuditContentResponse) ProtoMessage()               {}
func (*AuditContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

func (m *AuditContentResponse) GetContentId() uint64 {
	if m != nil {
		return m.ContentId
	}
	return 0
}

func (m *AuditContentResponse) GetResult() EPostResult {
	if m != nil {
		return m.Result
	}
	return EPostResult_E_PostResult_OK
}

func (m *AuditContentResponse) GetAuditResult() EAuditResult {
	if m != nil {
		return m.AuditResult
	}
	return EAuditResult_E_AuditResult_Pass
}

func init() {
	proto.RegisterType((*PostVideo)(nil), "budao.PostVideo")
	proto.RegisterType((*PostVideoResult)(nil), "budao.PostVideoResult")
	proto.RegisterType((*PostVideosRequest)(nil), "budao.PostVideosRequest")
	proto.RegisterType((*PostVideosResponse)(nil), "budao.PostVideosResponse")
	proto.RegisterType((*AuditContentRequest)(nil), "budao.AuditContentRequest")
	proto.RegisterType((*AuditContentResponse)(nil), "budao.AuditContentResponse")
	proto.RegisterEnum("budao.EVideoSource", EVideoSource_name, EVideoSource_value)
	proto.RegisterEnum("budao.EPostResult", EPostResult_name, EPostResult_value)
	proto.RegisterEnum("budao.EAuditResult", EAuditResult_name, EAuditResult_value)
}

func init() { proto.RegisterFile("transfer.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 813 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xd1, 0x72, 0xda, 0x46,
	0x14, 0xb5, 0x00, 0x63, 0xb8, 0x50, 0xbc, 0xbd, 0x76, 0x3c, 0xb2, 0x1c, 0x27, 0x84, 0xe9, 0x03,
	0xc3, 0x03, 0x0f, 0x74, 0xa6, 0x7d, 0x4c, 0x85, 0x51, 0x41, 0x21, 0x91, 0x18, 0x81, 0xe2, 0xc4,
	0x2f, 0x1a, 0x19, 0x6d, 0x6b, 0x75, 0x08, 0x52, 0x56, 0x12, 0x6d, 0xda, 0xff, 0xe8, 0x4c, 0x5f,
	0x3b, 0xd3, 0x3f, 0xea, 0x47, 0xf4, 0x33, 0x3a, 0x92, 0x16, 0x10, 0x58, 0x4c, 0xa6, 0xd3, 0x37,
	0xdd, 0x73, 0xce, 0xde, 0x7b, 0xf6, 0x68, 0xb5, 0x82, 0x46, 0xc8, 0xec, 0x65, 0xf0, 0x03, 0x65,
	0x5d, 0x9f, 0x79, 0xa1, 0x87, 0xc7, 0xf7, 0x91, 0x63, 0x7b, 0x52, 0xc3, 0xb7, 0x59, 0x40, 0x23,
	0xb6, 0x48, 0xe1, 0xd6, 0xdf, 0x05, 0xa8, 0x4e, 0xbc, 0x20, 0x7c, 0xeb, 0x3a, 0xd4, 0xc3, 0x6b,
	0x80, 0xc0, 0x8b, 0xd8, 0x9c, 0x5a, 0x2b, 0xd7, 0x11, 0x85, 0xa6, 0xd0, 0xae, 0x1a, 0xd5, 0x14,
	0x79, 0xeb, 0x3a, 0xf8, 0x1c, 0x6a, 0xab, 0x0c, 0x5f, 0x48, 0x78, 0x58, 0x6d, 0x05, 0x04, 0x8a,
	0xbe, 0x3b, 0x17, 0x8b, 0x09, 0x11, 0x3f, 0xe2, 0x15, 0x54, 0x57, 0x71, 0x6b, 0x2b, 0x62, 0x0b,
	0xb1, 0x94, 0xe0, 0x95, 0x04, 0x30, 0xd9, 0x02, 0xcf, 0xe1, 0x38, 0x74, 0xc3, 0x05, 0x15, 0x8f,
	0x13, 0x22, 0x2d, 0x62, 0xf4, 0x67, 0xd7, 0x09, 0x1f, 0xc4, 0x72, 0x53, 0x68, 0x7f, 0x61, 0xa4,
	0x05, 0x5e, 0x40, 0xf9, 0x81, 0xba, 0x3f, 0x3e, 0x84, 0xe2, 0x49, 0x02, 0xf3, 0x0a, 0x25, 0xa8,
	0x38, 0x11, 0xb3, 0x43, 0xd7, 0x5b, 0x8a, 0x95, 0x84, 0xd9, 0xd4, 0xf8, 0x2d, 0xd4, 0x69, 0xb2,
	0xb1, 0x69, 0xe2, 0x50, 0xac, 0x36, 0x85, 0x76, 0xa3, 0x77, 0xd6, 0x4d, 0xa2, 0xe8, 0x2a, 0x19,
	0xca, 0xd8, 0x11, 0xe2, 0x4b, 0x38, 0x4d, 0xeb, 0x49, 0x9c, 0x96, 0x11, 0x2d, 0xa8, 0x08, 0xc9,
	0xda, 0x27, 0x7c, 0xed, 0x2e, 0x69, 0xec, 0xab, 0x5b, 0xff, 0x08, 0x70, 0xba, 0x89, 0xd5, 0xa0,
	0x41, 0xb4, 0x08, 0xe3, 0x70, 0xb6, 0xa9, 0xc6, 0x8f, 0x7b, 0x71, 0x17, 0xf6, 0xe3, 0xde, 0xb7,
	0x5f, 0xfc, 0x1f, 0xf6, 0x4b, 0xff, 0xc5, 0x3e, 0x76, 0xa0, 0xcc, 0x12, 0xd3, 0xc9, 0x9b, 0x69,
	0xf4, 0x70, 0x3d, 0x33, 0xde, 0x53, 0xba, 0x1d, 0x83, 0x2b, 0x5a, 0x2f, 0xe1, 0xcb, 0xcd, 0x4e,
	0x03, 0x83, 0x7e, 0x8c, 0x68, 0x10, 0x62, 0x07, 0x4e, 0x38, 0x22, 0x0a, 0xcd, 0x62, 0xbb, 0xd6,
	0x23, 0xbc, 0xc3, 0x36, 0x94, 0xb5, 0xa0, 0x35, 0x02, 0xcc, 0x36, 0x08, 0x7c, 0x6f, 0x19, 0x50,
	0xec, 0x41, 0x85, 0x4f, 0x5a, 0xb7, 0xb8, 0x78, 0xd4, 0x22, 0x35, 0xb2, 0xd1, 0xb5, 0x3e, 0xc2,
	0x99, 0x1c, 0x39, 0x6e, 0x78, 0xe3, 0x2d, 0x43, 0xba, 0x0c, 0xd7, 0x66, 0xae, 0x01, 0xe6, 0x29,
	0x62, 0xf1, 0xfc, 0x4b, 0x46, 0x95, 0x23, 0xaa, 0x83, 0x22, 0x9c, 0xf0, 0x82, 0xbf, 0x82, 0x75,
	0x89, 0x2f, 0xa0, 0xbe, 0x5e, 0x18, 0x7e, 0xf2, 0x29, 0x3f, 0xd7, 0x35, 0x8e, 0xcd, 0x3e, 0xf9,
	0xb4, 0xf5, 0x87, 0x00, 0xe7, 0xbb, 0x33, 0xb9, 0xff, 0xcf, 0x0c, 0xdd, 0x26, 0x5c, 0xf8, 0x5c,
	0xc2, 0xf8, 0x0d, 0xd4, 0xed, 0x78, 0x84, 0xc5, 0x57, 0xec, 0x9d, 0x83, 0x64, 0x3c, 0x5f, 0x52,
	0xb3, 0xb7, 0x45, 0xe7, 0xaf, 0x12, 0xd4, 0xb3, 0xa7, 0x04, 0xaf, 0xe1, 0x52, 0xb1, 0x32, 0x80,
	0x75, 0x63, 0xc8, 0xb7, 0xaf, 0xad, 0x77, 0xea, 0xd0, 0x94, 0xc9, 0x11, 0x3e, 0x03, 0x29, 0x8f,
	0x1e, 0xe8, 0xe6, 0x7b, 0x55, 0x23, 0x02, 0x36, 0xe1, 0x69, 0x1e, 0x3f, 0x36, 0x65, 0x75, 0x3a,
	0xd2, 0x4d, 0x52, 0xc0, 0xaf, 0xa0, 0x99, 0xa7, 0xd0, 0x14, 0x75, 0x24, 0x6b, 0x03, 0x53, 0xd6,
	0xee, 0x54, 0x52, 0xc4, 0xa7, 0x20, 0xe6, 0xa9, 0x5e, 0xa9, 0x63, 0x85, 0x94, 0x0e, 0xb9, 0x18,
	0xc9, 0xfa, 0x58, 0xd6, 0xc8, 0xf1, 0xa1, 0xd5, 0x7d, 0xbd, 0xaf, 0x93, 0x32, 0x3e, 0x87, 0xab,
	0x3c, 0xf6, 0x8d, 0x2a, 0xeb, 0x13, 0x59, 0x25, 0x27, 0x87, 0xda, 0xbf, 0x51, 0xd4, 0x98, 0xaf,
	0x1c, 0xca, 0xa8, 0x7f, 0x37, 0x92, 0x35, 0x52, 0x3d, 0x44, 0xdf, 0x2a, 0x6a, 0x5f, 0x27, 0x80,
	0x12, 0x5c, 0xe4, 0xd1, 0xaf, 0x55, 0x52, 0xc3, 0x16, 0x3c, 0xcb, 0xe3, 0xbe, 0x57, 0xd4, 0x81,
	0xaa, 0x4c, 0x47, 0xa6, 0x4e, 0xea, 0xf8, 0x02, 0xae, 0xf3, 0x34, 0xef, 0x65, 0x6d, 0x38, 0x34,
	0x65, 0x6d, 0x48, 0x1a, 0x78, 0x09, 0x4f, 0x76, 0x25, 0xfa, 0xad, 0x66, 0xe9, 0x93, 0x29, 0x99,
	0xe7, 0x53, 0x37, 0x03, 0x8d, 0x38, 0x8f, 0x8d, 0xc5, 0xd4, 0x4c, 0x99, 0xce, 0x08, 0xed, 0xfc,
	0x06, 0xb5, 0xcc, 0xb1, 0xc3, 0x33, 0x38, 0x55, 0xac, 0x6d, 0x6d, 0xe9, 0x63, 0x72, 0x94, 0xee,
	0x3b, 0x03, 0x4e, 0x29, 0x5b, 0x51, 0x66, 0x29, 0x8c, 0x79, 0x8c, 0x08, 0x8f, 0xe8, 0x89, 0xcd,
	0xec, 0x0f, 0x01, 0xa7, 0x0b, 0xa9, 0xb1, 0x0c, 0x6d, 0x50, 0x9f, 0xda, 0x21, 0x75, 0x48, 0xb1,
	0xf3, 0x1d, 0xd4, 0xb3, 0x27, 0x18, 0x2f, 0x00, 0x15, 0x2b, 0x03, 0x58, 0x13, 0x3b, 0x08, 0xc8,
	0x11, 0x8a, 0x70, 0xbe, 0x8b, 0x9b, 0x4b, 0x3f, 0x66, 0x84, 0xde, 0xef, 0x02, 0x54, 0x66, 0xfc,
	0x67, 0x87, 0x32, 0xc0, 0xf6, 0x32, 0x41, 0x71, 0xff, 0xca, 0x58, 0x5f, 0x50, 0xd2, 0x65, 0x0e,
	0xc3, 0xbf, 0xdc, 0x21, 0xd4, 0xb3, 0x5f, 0x34, 0x4a, 0x5c, 0x9a, 0x73, 0xb5, 0x48, 0x57, 0xb9,
	0x5c, 0xda, 0xa8, 0x2f, 0x01, 0x99, 0x7b, 0x1f, 0xba, 0x3f, 0xfd, 0xf2, 0x6b, 0xd7, 0xbf, 0x4f,
	0x85, 0x13, 0xe1, 0xcf, 0x42, 0xf1, 0xd5, 0xbb, 0xbb, 0xfb, 0x72, 0xf2, 0xfb, 0xfd, 0xfa, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0xcd, 0x36, 0x50, 0xa7, 0x07, 0x00, 0x00,
}
