// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bannerService.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	bannerService.proto
	blacklistService.proto
	common.proto
	commonService.proto
	keywordService.proto
	nlpService.proto
	pushService.proto
	reportService.proto
	simComment.proto
	spiderService.proto
	topicService.proto
	userService.proto
	videoService.proto
	wechatService.proto

It has these top-level messages:
	BannerDelRequest
	BannerInfoRequest
	BannerInfoResponse
	BannerListResponse
	BannerList
	RemoveUserCommonReq
	UnlockUserReq
	AddBlackListReq
	BlackList
	BlacklistUserListResponse
	BlackListUserList
	QueryListRequest
	CommonResponse
	NullReq
	Comment
	CommentListResponse
	CommentList
	CommentListReq
	VideoListResponse
	VideoList
	Video
	Banner
	User
	Question
	QuestionOption
	Topic
	TopicVideo
	Push
	Rule
	CategoryListResponse
	QuestionCategory
	TypeListResponse
	QuestionType
	AddCategoryReq
	AddTypeReq
	InternalUserListResponse
	UserList
	QueryCommentContentReq
	OptionCommentContentReq
	OptionVideoTitleReq
	SimCommentResponse
	SimCommentRequest
	PushDelRequest
	PushInfoRequest
	PushInfoResponse
	PushListResponse
	PushList
	ReportVideoExeclResponse
	ReportVideoExeclBack
	ReportUserExeclResponse
	ReportUserExeclBack
	ReportVideoStatisticsResponse
	ReportVideoStatisticsBack
	StatisBizDaily
	ReportUserStatisticsResponse
	ReportUserStatisticsBack
	StatisUser
	ReportContentTopicDataResponse
	ReportContentTopicDataBack
	TopicOther
	ReportContentPostDataResponse
	ReportContentPostDataBack
	ReportPushVVListRequest
	ReportPushVVListResponse
	ReportPushVVListBack
	ReportPushVVRequest
	ReportPushVVResponse
	ReportPushVVBack
	ReportOpTodayResponse
	ReportOpBack
	Sentence
	SimSentResponse
	SimSentInput
	ModifyResponse
	Identity
	PostVideResponse
	ModifyCommentStatusRequest
	PostCommentRequest
	PostAllCommentReques
	TopicRulePostVideoRequest
	TopicRuleViewListResponse
	ViewList
	TopicRuleMediaNameResponse
	MediaName
	MediaNameMessage
	TopicRuleInfoRequest
	TopicRuleInfoResponse
	TopicRuleDelRequest
	TopicRuleRequest
	TopicRuleListResponse
	TopicRuleList
	TopicBack
	TopicRuleMessage
	ReportCommentOperaRequest
	ReportCommentResponse
	ReportCommentList
	ReportCommentMessage
	FeedbackListResponse
	FeedbackList
	FeedbackMessage
	ReportVideoOperaRequest
	ReportVideoResponse
	ReportVideoList
	ReportVideoMessage
	QuestionListResponse
	QuestionList
	GetQuestionResponse
	AuditVideoOfflineReq
	TopicListResponse
	TopicList
	TopicInfoResponse
	CommentModifyStateReq
	CommentInfoResponse
	CommentAddReq
	VideoReviewReq
	GetTopicRuleReq
	GetTopicRuleResponse
	RuleName
	WechatRedirectRequest
	WechatRedirectResponse
	BackStruct
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// banner删除
type BannerDelRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *BannerDelRequest) Reset()                    { *m = BannerDelRequest{} }
func (m *BannerDelRequest) String() string            { return proto.CompactTextString(m) }
func (*BannerDelRequest) ProtoMessage()               {}
func (*BannerDelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BannerDelRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// banner信息
type BannerInfoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *BannerInfoRequest) Reset()                    { *m = BannerInfoRequest{} }
func (m *BannerInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*BannerInfoRequest) ProtoMessage()               {}
func (*BannerInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BannerInfoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type BannerInfoResponse struct {
	Code string  `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data *Banner `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *BannerInfoResponse) Reset()                    { *m = BannerInfoResponse{} }
func (m *BannerInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*BannerInfoResponse) ProtoMessage()               {}
func (*BannerInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BannerInfoResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *BannerInfoResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BannerInfoResponse) GetData() *Banner {
	if m != nil {
		return m.Data
	}
	return nil
}

// banner列表
type BannerListResponse struct {
	Code string      `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data *BannerList `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *BannerListResponse) Reset()                    { *m = BannerListResponse{} }
func (m *BannerListResponse) String() string            { return proto.CompactTextString(m) }
func (*BannerListResponse) ProtoMessage()               {}
func (*BannerListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BannerListResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *BannerListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *BannerListResponse) GetData() *BannerList {
	if m != nil {
		return m.Data
	}
	return nil
}

type BannerList struct {
	Data  []*Banner `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Count uint64    `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *BannerList) Reset()                    { *m = BannerList{} }
func (m *BannerList) String() string            { return proto.CompactTextString(m) }
func (*BannerList) ProtoMessage()               {}
func (*BannerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BannerList) GetData() []*Banner {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BannerList) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*BannerDelRequest)(nil), "api.BannerDelRequest")
	proto.RegisterType((*BannerInfoRequest)(nil), "api.BannerInfoRequest")
	proto.RegisterType((*BannerInfoResponse)(nil), "api.BannerInfoResponse")
	proto.RegisterType((*BannerListResponse)(nil), "api.BannerListResponse")
	proto.RegisterType((*BannerList)(nil), "api.BannerList")
}

func init() { proto.RegisterFile("bannerService.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x3f, 0x4f, 0xfb, 0x30,
	0x14, 0x54, 0x92, 0xfe, 0x7e, 0x52, 0x5f, 0x0b, 0x94, 0x57, 0xfe, 0x54, 0x59, 0x88, 0xd2, 0xa5,
	0x0b, 0x11, 0x2a, 0x03, 0x0b, 0x0c, 0xb4, 0x5d, 0x90, 0x60, 0x20, 0x8c, 0x0c, 0x28, 0x89, 0x5d,
	0x64, 0xa9, 0xb1, 0x43, 0xfe, 0x20, 0xf5, 0x0b, 0xf1, 0x39, 0x51, 0x9f, 0x9b, 0xd6, 0xa9, 0x8a,
	0x04, 0x9b, 0xfd, 0x7c, 0x77, 0xbe, 0xf3, 0x19, 0xfa, 0x71, 0x24, 0x25, 0xcf, 0x5f, 0x78, 0xfe,
	0x29, 0x12, 0x1e, 0x64, 0xb9, 0x2a, 0x15, 0x3a, 0x51, 0x26, 0xdc, 0x6e, 0xa2, 0xd2, 0x54, 0x49,
	0x3d, 0xf2, 0x7d, 0xe8, 0x4d, 0x08, 0x39, 0xe3, 0x8b, 0x90, 0x7f, 0x54, 0xbc, 0x28, 0xf1, 0x10,
	0x6c, 0xc1, 0x06, 0x96, 0x67, 0x8d, 0xda, 0xa1, 0x2d, 0x98, 0x3f, 0x84, 0x63, 0x8d, 0x79, 0x90,
	0x73, 0xf5, 0x13, 0xe8, 0x15, 0xd0, 0x04, 0x15, 0x99, 0x92, 0x05, 0x47, 0x84, 0x56, 0xa2, 0x18,
	0x5f, 0xe3, 0x68, 0x8d, 0x3d, 0x70, 0xd2, 0xe2, 0x7d, 0x60, 0xd3, 0x68, 0xb5, 0xc4, 0x0b, 0x68,
	0xb1, 0xa8, 0x8c, 0x06, 0x8e, 0x67, 0x8d, 0x3a, 0xe3, 0x4e, 0x10, 0x65, 0x22, 0xd0, 0x62, 0x21,
	0x1d, 0xf8, 0x6f, 0xb5, 0xf8, 0xa3, 0x28, 0xca, 0x3f, 0x8a, 0x0f, 0x1b, 0xe2, 0x47, 0x86, 0x38,
	0x89, 0xe9, 0x0b, 0xa6, 0x00, 0xdb, 0xd9, 0xc6, 0x8f, 0xe5, 0x39, 0x7b, 0xfd, 0xe0, 0x09, 0xfc,
	0x4b, 0x54, 0x25, 0x4b, 0xba, 0xa7, 0x15, 0xea, 0xcd, 0xf8, 0xcb, 0x86, 0x83, 0x89, 0xf9, 0xec,
	0x78, 0x09, 0x6d, 0xdd, 0xc3, 0x3d, 0x63, 0x68, 0xea, 0xb8, 0x7d, 0xda, 0x4c, 0xa9, 0x8a, 0x4d,
	0xa0, 0x5b, 0x80, 0x78, 0xeb, 0xe2, 0x94, 0x20, 0xcf, 0x15, 0xcf, 0x97, 0x3a, 0x36, 0x3d, 0xbc,
	0x7b, 0xbe, 0x9b, 0xa0, 0x66, 0xdf, 0xd5, 0xec, 0x55, 0x03, 0x78, 0x66, 0xc0, 0x8c, 0xde, 0x1a,
	0xf4, 0x46, 0x55, 0x57, 0xd0, 0xd5, 0xf4, 0x27, 0xc5, 0xc4, 0x7c, 0xf9, 0x0b, 0xbb, 0x37, 0x75,
	0xba, 0x19, 0x5f, 0xac, 0xdd, 0xee, 0xfe, 0xa5, 0xbd, 0xc4, 0xf8, 0x3f, 0xfd, 0xbd, 0xeb, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x85, 0xde, 0xf2, 0xa5, 0x02, 0x00, 0x00,
}
