#!/bin/bash

arg='-p'
if [ $# -ge 1 ];
then
    arg=$1
fi
#echo "arg is :" $arg

count=1
APP_NAME="recommend-server"

function stop() {
    if [ $(pidof $APP_NAME |wc -w) -eq 0 ] ; then
        echo "no running $APP_NAME found, already stopped"
        return
    fi
    pid=$(pidof $APP_NAME)
    for i in $pid ; do
        echo "kill $APP_NAME pid=$i [$(ps --no-headers -lf $i)]"
        sudo kill -9 $i
        [ $? -eq 0 ] && ( echo "kill success" ) &
        sleep 1
    done
    if [ -z "$(pidof $APP_NAME)" ] ; then
        echo "stop $APP_NAME ok, all $APP_NAME got killed"
        #echo "output last 20 lines of $log"
        #tail -n 20 $log
        return
    fi
}

function start() {
    if [ $(pidof $APP_NAME |wc -w) -eq $count ]; then
        echo "$APP_NAME is running"
        return
    fi
    cd ~/budao-server/recommend
    nohup sudo ./${APP_NAME} -c ./conf/cfg-test.json > /tmp/${APP_NAME}.log 2>&1 &
    sleep 2
    if [ $(pidof $APP_NAME | wc -w) -eq $count ]; then
        echo "$APP_NAME start"
    fi
    ps aux | grep ${APP_NAME}
}

case $arg in
    '-s')
        stop
        ;;
    '-r')
        start
        ;;
    '-os')
        sudo /bin/bash /data/services/recommend-server/admin/stop.sh
        ;;
    '-or')
        sudo /bin/bash /data/services/recommend-server/admin/restart.sh
        ;;
    '-m')
        cd ~/budao-server/recommend
        make
        if [ $? -ne 0 ];then
            exit -1
        fi
        stop
        start
        ;;
    '-p')
        ps aux | grep ${APP_NAME}
        ;;
    '-t')
        sudo tail -f /data/budao-server/logs/${APP_NAME}.log
        ;;
    '-te')
        sudo tail -f /data/budao-server/logs/${APP_NAME}.log | grep '\[E\]'
        ;;
    '-v')
        GITVERSION=`/usr/bin/git rev-list --all|wc -l`
        echo ${GITVERSION}
        ;;
    '-c')
        sudo rm -f /data/services/recommend-server/conf/default_index
        sudo cp -f ~/default_index /data/services/recommend-server/conf/
        cd /data/services/recommend-server/admin
        sudo ./restart.sh
        ;;
    '-h')
        echo "-s stop"
        echo "-r restart"
        echo "-m make stop start"
        echo "-p ps aux |grep budao"
        echo "-t tail -f /data/budao-server/logs/${APP_NAME}.log"
        ;;
esac

