// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package budao is a generated protocol buffer package.

It is generated from these files:
	common.proto
	share.proto

It has these top-level messages:
	DeviceIOSInfo
	DeviceAndroidInfo
	DeviceInfo
	EnvironmentInfo
	Header
	Status
	ShareItem
	TopicItem
	VideoItem
	OptionItem
	QuestionItem
	UserItem
	CommentItem
	ReplyItem
	ArticleItem
	RecommendItem
	SwitchItem
	ListItem
	ChannelItem
	TabItem
	ShareVideoBottomPageRequest
	ShareVideoBottomPageResponse
	ShareTopicPageRequest
	ShareTopicPageResponse
*/
package budao

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 网络类型
type Network int32

const (
	Network_NET_2G Network = 0
	Network_NET_3G Network = 1
	Network_NET_4G Network = 2
	Network_NET_5G Network = 3
	Network_WIFI   Network = 4
	Network_OTHER  Network = 5
)

var Network_name = map[int32]string{
	0: "NET_2G",
	1: "NET_3G",
	2: "NET_4G",
	3: "NET_5G",
	4: "WIFI",
	5: "OTHER",
}
var Network_value = map[string]int32{
	"NET_2G": 0,
	"NET_3G": 1,
	"NET_4G": 2,
	"NET_5G": 3,
	"WIFI":   4,
	"OTHER":  5,
}

func (x Network) String() string {
	return proto.EnumName(Network_name, int32(x))
}
func (Network) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 列表刷新方向
type Direction int32

const (
	Direction_ALL    Direction = 0
	Direction_TOP    Direction = 1
	Direction_BOTTOM Direction = 2
)

var Direction_name = map[int32]string{
	0: "ALL",
	1: "TOP",
	2: "BOTTOM",
}
var Direction_value = map[string]int32{
	"ALL":    0,
	"TOP":    1,
	"BOTTOM": 2,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}
func (Direction) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DeviceInfo_Type int32

const (
	DeviceInfo_ANDROID DeviceInfo_Type = 0
	DeviceInfo_IOS     DeviceInfo_Type = 1
)

var DeviceInfo_Type_name = map[int32]string{
	0: "ANDROID",
	1: "IOS",
}
var DeviceInfo_Type_value = map[string]int32{
	"ANDROID": 0,
	"IOS":     1,
}

func (x DeviceInfo_Type) String() string {
	return proto.EnumName(DeviceInfo_Type_name, int32(x))
}
func (DeviceInfo_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type Status_Code int32

const (
	Status_OK                         Status_Code = 0
	Status_SERVER_ERR                 Status_Code = 1
	Status_BAD_REQUEST                Status_Code = 2
	Status_USER_NOTLOGIN              Status_Code = 101
	Status_TOPIC_REPEATED_SUBSCRIBED  Status_Code = 102
	Status_QUESTION_REPEATED_ANSWERED Status_Code = 103
	Status_VIDEO_REPEATED_LIKED       Status_Code = 104
	Status_COMMENT_REPEATED_LIKED     Status_Code = 105
)

var Status_Code_name = map[int32]string{
	0:   "OK",
	1:   "SERVER_ERR",
	2:   "BAD_REQUEST",
	101: "USER_NOTLOGIN",
	102: "TOPIC_REPEATED_SUBSCRIBED",
	103: "QUESTION_REPEATED_ANSWERED",
	104: "VIDEO_REPEATED_LIKED",
	105: "COMMENT_REPEATED_LIKED",
}
var Status_Code_value = map[string]int32{
	"OK":                         0,
	"SERVER_ERR":                 1,
	"BAD_REQUEST":                2,
	"USER_NOTLOGIN":              101,
	"TOPIC_REPEATED_SUBSCRIBED":  102,
	"QUESTION_REPEATED_ANSWERED": 103,
	"VIDEO_REPEATED_LIKED":       104,
	"COMMENT_REPEATED_LIKED":     105,
}

func (x Status_Code) String() string {
	return proto.EnumName(Status_Code_name, int32(x))
}
func (Status_Code) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type QuestionItem_Style int32

const (
	QuestionItem_SINGLE QuestionItem_Style = 0
	QuestionItem_DOUBLE QuestionItem_Style = 1
)

var QuestionItem_Style_name = map[int32]string{
	0: "SINGLE",
	1: "DOUBLE",
}
var QuestionItem_Style_value = map[string]int32{
	"SINGLE": 0,
	"DOUBLE": 1,
}

func (x QuestionItem_Style) String() string {
	return proto.EnumName(QuestionItem_Style_name, int32(x))
}
func (QuestionItem_Style) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{10, 0} }

type SwitchItem_FullscreenType int32

const (
	SwitchItem_PORTRAIT  SwitchItem_FullscreenType = 0
	SwitchItem_LANDSCAPE SwitchItem_FullscreenType = 1
)

var SwitchItem_FullscreenType_name = map[int32]string{
	0: "PORTRAIT",
	1: "LANDSCAPE",
}
var SwitchItem_FullscreenType_value = map[string]int32{
	"PORTRAIT":  0,
	"LANDSCAPE": 1,
}

func (x SwitchItem_FullscreenType) String() string {
	return proto.EnumName(SwitchItem_FullscreenType_name, int32(x))
}
func (SwitchItem_FullscreenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16, 0}
}

// iOS设备信息
type DeviceIOSInfo struct {
	Idfv string `protobuf:"bytes,1,opt,name=idfv" json:"idfv,omitempty"`
	Idfa string `protobuf:"bytes,2,opt,name=idfa" json:"idfa,omitempty"`
	Guid string `protobuf:"bytes,3,opt,name=guid" json:"guid,omitempty"`
}

func (m *DeviceIOSInfo) Reset()                    { *m = DeviceIOSInfo{} }
func (m *DeviceIOSInfo) String() string            { return proto.CompactTextString(m) }
func (*DeviceIOSInfo) ProtoMessage()               {}
func (*DeviceIOSInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceIOSInfo) GetIdfv() string {
	if m != nil {
		return m.Idfv
	}
	return ""
}

func (m *DeviceIOSInfo) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *DeviceIOSInfo) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

// 安卓设备信息
type DeviceAndroidInfo struct {
	AndroidId string `protobuf:"bytes,1,opt,name=android_id,json=androidId" json:"android_id,omitempty"`
	Imei      string `protobuf:"bytes,2,opt,name=imei" json:"imei,omitempty"`
	Imsi      string `protobuf:"bytes,3,opt,name=imsi" json:"imsi,omitempty"`
	Guid      string `protobuf:"bytes,4,opt,name=guid" json:"guid,omitempty"`
}

func (m *DeviceAndroidInfo) Reset()                    { *m = DeviceAndroidInfo{} }
func (m *DeviceAndroidInfo) String() string            { return proto.CompactTextString(m) }
func (*DeviceAndroidInfo) ProtoMessage()               {}
func (*DeviceAndroidInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceAndroidInfo) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *DeviceAndroidInfo) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *DeviceAndroidInfo) GetImsi() string {
	if m != nil {
		return m.Imsi
	}
	return ""
}

func (m *DeviceAndroidInfo) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

// 设备信息
type DeviceInfo struct {
	DeviceId   string          `protobuf:"bytes,1,opt,name=device_id,json=deviceId" json:"device_id,omitempty"`
	AppVersion string          `protobuf:"bytes,2,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	DeviceType DeviceInfo_Type `protobuf:"varint,3,opt,name=device_type,json=deviceType,enum=budao.DeviceInfo_Type" json:"device_type,omitempty"`
	OsVersion  string          `protobuf:"bytes,4,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	// Types that are valid to be assigned to Device:
	//	*DeviceInfo_Ios
	//	*DeviceInfo_Android
	Device isDeviceInfo_Device `protobuf_oneof:"Device"`
}

func (m *DeviceInfo) Reset()                    { *m = DeviceInfo{} }
func (m *DeviceInfo) String() string            { return proto.CompactTextString(m) }
func (*DeviceInfo) ProtoMessage()               {}
func (*DeviceInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isDeviceInfo_Device interface {
	isDeviceInfo_Device()
}

type DeviceInfo_Ios struct {
	Ios *DeviceIOSInfo `protobuf:"bytes,5,opt,name=ios,oneof"`
}
type DeviceInfo_Android struct {
	Android *DeviceAndroidInfo `protobuf:"bytes,6,opt,name=android,oneof"`
}

func (*DeviceInfo_Ios) isDeviceInfo_Device()     {}
func (*DeviceInfo_Android) isDeviceInfo_Device() {}

func (m *DeviceInfo) GetDevice() isDeviceInfo_Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *DeviceInfo) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceInfo) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *DeviceInfo) GetDeviceType() DeviceInfo_Type {
	if m != nil {
		return m.DeviceType
	}
	return DeviceInfo_ANDROID
}

func (m *DeviceInfo) GetOsVersion() string {
	if m != nil {
		return m.OsVersion
	}
	return ""
}

func (m *DeviceInfo) GetIos() *DeviceIOSInfo {
	if x, ok := m.GetDevice().(*DeviceInfo_Ios); ok {
		return x.Ios
	}
	return nil
}

func (m *DeviceInfo) GetAndroid() *DeviceAndroidInfo {
	if x, ok := m.GetDevice().(*DeviceInfo_Android); ok {
		return x.Android
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DeviceInfo) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DeviceInfo_OneofMarshaler, _DeviceInfo_OneofUnmarshaler, _DeviceInfo_OneofSizer, []interface{}{
		(*DeviceInfo_Ios)(nil),
		(*DeviceInfo_Android)(nil),
	}
}

func _DeviceInfo_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DeviceInfo)
	// Device
	switch x := m.Device.(type) {
	case *DeviceInfo_Ios:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ios); err != nil {
			return err
		}
	case *DeviceInfo_Android:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Android); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("DeviceInfo.Device has unexpected type %T", x)
	}
	return nil
}

func _DeviceInfo_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DeviceInfo)
	switch tag {
	case 5: // Device.ios
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceIOSInfo)
		err := b.DecodeMessage(msg)
		m.Device = &DeviceInfo_Ios{msg}
		return true, err
	case 6: // Device.android
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeviceAndroidInfo)
		err := b.DecodeMessage(msg)
		m.Device = &DeviceInfo_Android{msg}
		return true, err
	default:
		return false, nil
	}
}

func _DeviceInfo_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DeviceInfo)
	// Device
	switch x := m.Device.(type) {
	case *DeviceInfo_Ios:
		s := proto.Size(x.Ios)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *DeviceInfo_Android:
		s := proto.Size(x.Android)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 环境信息
type EnvironmentInfo struct {
	Network      Network `protobuf:"varint,1,opt,name=network,enum=budao.Network" json:"network,omitempty"`
	LaunchType   string  `protobuf:"bytes,2,opt,name=launch_type,json=launchType" json:"launch_type,omitempty"`
	ExperimentId uint32  `protobuf:"varint,3,opt,name=experiment_id,json=experimentId" json:"experiment_id,omitempty"`
	Store        string  `protobuf:"bytes,4,opt,name=store" json:"store,omitempty"`
}

func (m *EnvironmentInfo) Reset()                    { *m = EnvironmentInfo{} }
func (m *EnvironmentInfo) String() string            { return proto.CompactTextString(m) }
func (*EnvironmentInfo) ProtoMessage()               {}
func (*EnvironmentInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnvironmentInfo) GetNetwork() Network {
	if m != nil {
		return m.Network
	}
	return Network_NET_2G
}

func (m *EnvironmentInfo) GetLaunchType() string {
	if m != nil {
		return m.LaunchType
	}
	return ""
}

func (m *EnvironmentInfo) GetExperimentId() uint32 {
	if m != nil {
		return m.ExperimentId
	}
	return 0
}

func (m *EnvironmentInfo) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

// 服务器请求带的公用信息
type Header struct {
	UserId          string           `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Token           string           `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	DeviceInfo      *DeviceInfo      `protobuf:"bytes,3,opt,name=device_info,json=deviceInfo" json:"device_info,omitempty"`
	EnvironmentInfo *EnvironmentInfo `protobuf:"bytes,4,opt,name=environment_info,json=environmentInfo" json:"environment_info,omitempty"`
	Timestamp       uint64           `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Header) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Header) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Header) GetDeviceInfo() *DeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

func (m *Header) GetEnvironmentInfo() *EnvironmentInfo {
	if m != nil {
		return m.EnvironmentInfo
	}
	return nil
}

func (m *Header) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// 服务器返回的公用状态信息
type Status struct {
	Code       Status_Code `protobuf:"varint,1,opt,name=code,enum=budao.Status_Code" json:"code,omitempty"`
	Message    string      `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	ServerTime uint64      `protobuf:"varint,3,opt,name=server_time,json=serverTime" json:"server_time,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Status) GetCode() Status_Code {
	if m != nil {
		return m.Code
	}
	return Status_OK
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetServerTime() uint64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type ShareItem struct {
	Title    string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Desc     string `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	IconUrl  string `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl" json:"icon_url,omitempty"`
	ShareUrl string `protobuf:"bytes,4,opt,name=share_url,json=shareUrl" json:"share_url,omitempty"`
	Text     string `protobuf:"bytes,5,opt,name=text" json:"text,omitempty"`
}

func (m *ShareItem) Reset()                    { *m = ShareItem{} }
func (m *ShareItem) String() string            { return proto.CompactTextString(m) }
func (*ShareItem) ProtoMessage()               {}
func (*ShareItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ShareItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ShareItem) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ShareItem) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *ShareItem) GetShareUrl() string {
	if m != nil {
		return m.ShareUrl
	}
	return ""
}

func (m *ShareItem) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

// 话题信息
type TopicItem struct {
	TopicId        string       `protobuf:"bytes,1,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	Name           string       `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	IconUrl        string       `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl" json:"icon_url,omitempty"`
	Desc           string       `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`
	Subscribed     bool         `protobuf:"varint,5,opt,name=subscribed" json:"subscribed,omitempty"`
	SubscribeCount uint32       `protobuf:"varint,6,opt,name=subscribe_count,json=subscribeCount" json:"subscribe_count,omitempty"`
	VideoItems     []*VideoItem `protobuf:"bytes,7,rep,name=video_items,json=videoItems" json:"video_items,omitempty"`
	ShareItem      *ShareItem   `protobuf:"bytes,8,opt,name=share_item,json=shareItem" json:"share_item,omitempty"`
	ShareDisabled  bool         `protobuf:"varint,9,opt,name=share_disabled,json=shareDisabled" json:"share_disabled,omitempty"`
}

func (m *TopicItem) Reset()                    { *m = TopicItem{} }
func (m *TopicItem) String() string            { return proto.CompactTextString(m) }
func (*TopicItem) ProtoMessage()               {}
func (*TopicItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *TopicItem) GetTopicId() string {
	if m != nil {
		return m.TopicId
	}
	return ""
}

func (m *TopicItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TopicItem) GetIconUrl() string {
	if m != nil {
		return m.IconUrl
	}
	return ""
}

func (m *TopicItem) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *TopicItem) GetSubscribed() bool {
	if m != nil {
		return m.Subscribed
	}
	return false
}

func (m *TopicItem) GetSubscribeCount() uint32 {
	if m != nil {
		return m.SubscribeCount
	}
	return 0
}

func (m *TopicItem) GetVideoItems() []*VideoItem {
	if m != nil {
		return m.VideoItems
	}
	return nil
}

func (m *TopicItem) GetShareItem() *ShareItem {
	if m != nil {
		return m.ShareItem
	}
	return nil
}

func (m *TopicItem) GetShareDisabled() bool {
	if m != nil {
		return m.ShareDisabled
	}
	return false
}

// 视频信息
type VideoItem struct {
	VideoId     string     `protobuf:"bytes,1,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	PictureUrl  string     `protobuf:"bytes,2,opt,name=picture_url,json=pictureUrl" json:"picture_url,omitempty"`
	Title       string     `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Width       uint32     `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
	Height      uint32     `protobuf:"varint,5,opt,name=height" json:"height,omitempty"`
	Duration    uint32     `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
	PublishTime uint64     `protobuf:"varint,7,opt,name=publish_time,json=publishTime" json:"publish_time,omitempty"`
	ShareItem   *ShareItem `protobuf:"bytes,8,opt,name=share_item,json=shareItem" json:"share_item,omitempty"`
}

func (m *VideoItem) Reset()                    { *m = VideoItem{} }
func (m *VideoItem) String() string            { return proto.CompactTextString(m) }
func (*VideoItem) ProtoMessage()               {}
func (*VideoItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *VideoItem) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *VideoItem) GetPictureUrl() string {
	if m != nil {
		return m.PictureUrl
	}
	return ""
}

func (m *VideoItem) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *VideoItem) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *VideoItem) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *VideoItem) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *VideoItem) GetPublishTime() uint64 {
	if m != nil {
		return m.PublishTime
	}
	return 0
}

func (m *VideoItem) GetShareItem() *ShareItem {
	if m != nil {
		return m.ShareItem
	}
	return nil
}

type OptionItem struct {
	OptionId    string `protobuf:"bytes,1,opt,name=option_id,json=optionId" json:"option_id,omitempty"`
	QuestionId  string `protobuf:"bytes,2,opt,name=question_id,json=questionId" json:"question_id,omitempty"`
	Content     string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Right       bool   `protobuf:"varint,4,opt,name=right" json:"right,omitempty"`
	ChooseCount uint32 `protobuf:"varint,5,opt,name=choose_count,json=chooseCount" json:"choose_count,omitempty"`
}

func (m *OptionItem) Reset()                    { *m = OptionItem{} }
func (m *OptionItem) String() string            { return proto.CompactTextString(m) }
func (*OptionItem) ProtoMessage()               {}
func (*OptionItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *OptionItem) GetOptionId() string {
	if m != nil {
		return m.OptionId
	}
	return ""
}

func (m *OptionItem) GetQuestionId() string {
	if m != nil {
		return m.QuestionId
	}
	return ""
}

func (m *OptionItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *OptionItem) GetRight() bool {
	if m != nil {
		return m.Right
	}
	return false
}

func (m *OptionItem) GetChooseCount() uint32 {
	if m != nil {
		return m.ChooseCount
	}
	return 0
}

// 问题信息
type QuestionItem struct {
	QuestionId     string             `protobuf:"bytes,1,opt,name=question_id,json=questionId" json:"question_id,omitempty"`
	VideoId        string             `protobuf:"bytes,2,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	HardLevel      uint32             `protobuf:"varint,3,opt,name=hard_level,json=hardLevel" json:"hard_level,omitempty"`
	Score          uint32             `protobuf:"varint,4,opt,name=score" json:"score,omitempty"`
	Content        string             `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	Options        []*OptionItem      `protobuf:"bytes,6,rep,name=options" json:"options,omitempty"`
	AnsweredCount  uint32             `protobuf:"varint,7,opt,name=answered_count,json=answeredCount" json:"answered_count,omitempty"`
	Style          QuestionItem_Style `protobuf:"varint,8,opt,name=style,enum=budao.QuestionItem_Style" json:"style,omitempty"`
	ChooseOptionId string             `protobuf:"bytes,9,opt,name=choose_option_id,json=chooseOptionId" json:"choose_option_id,omitempty"`
}

func (m *QuestionItem) Reset()                    { *m = QuestionItem{} }
func (m *QuestionItem) String() string            { return proto.CompactTextString(m) }
func (*QuestionItem) ProtoMessage()               {}
func (*QuestionItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QuestionItem) GetQuestionId() string {
	if m != nil {
		return m.QuestionId
	}
	return ""
}

func (m *QuestionItem) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *QuestionItem) GetHardLevel() uint32 {
	if m != nil {
		return m.HardLevel
	}
	return 0
}

func (m *QuestionItem) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *QuestionItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *QuestionItem) GetOptions() []*OptionItem {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *QuestionItem) GetAnsweredCount() uint32 {
	if m != nil {
		return m.AnsweredCount
	}
	return 0
}

func (m *QuestionItem) GetStyle() QuestionItem_Style {
	if m != nil {
		return m.Style
	}
	return QuestionItem_SINGLE
}

func (m *QuestionItem) GetChooseOptionId() string {
	if m != nil {
		return m.ChooseOptionId
	}
	return ""
}

// 用户信息
type UserItem struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	PhotoUrl string `protobuf:"bytes,3,opt,name=photo_url,json=photoUrl" json:"photo_url,omitempty"`
}

func (m *UserItem) Reset()                    { *m = UserItem{} }
func (m *UserItem) String() string            { return proto.CompactTextString(m) }
func (*UserItem) ProtoMessage()               {}
func (*UserItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UserItem) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserItem) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

// 评论信息
type CommentItem struct {
	CommentId   string       `protobuf:"bytes,1,opt,name=comment_id,json=commentId" json:"comment_id,omitempty"`
	VideoId     string       `protobuf:"bytes,2,opt,name=video_id,json=videoId" json:"video_id,omitempty"`
	UserItem    *UserItem    `protobuf:"bytes,3,opt,name=user_item,json=userItem" json:"user_item,omitempty"`
	Content     string       `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	ReplyCount  uint32       `protobuf:"varint,5,opt,name=reply_count,json=replyCount" json:"reply_count,omitempty"`
	ReplyItems  []*ReplyItem `protobuf:"bytes,6,rep,name=reply_items,json=replyItems" json:"reply_items,omitempty"`
	LikeCount   uint32       `protobuf:"varint,7,opt,name=like_count,json=likeCount" json:"like_count,omitempty"`
	Liked       bool         `protobuf:"varint,8,opt,name=liked" json:"liked,omitempty"`
	CommentTime uint64       `protobuf:"varint,9,opt,name=comment_time,json=commentTime" json:"comment_time,omitempty"`
}

func (m *CommentItem) Reset()                    { *m = CommentItem{} }
func (m *CommentItem) String() string            { return proto.CompactTextString(m) }
func (*CommentItem) ProtoMessage()               {}
func (*CommentItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *CommentItem) GetCommentId() string {
	if m != nil {
		return m.CommentId
	}
	return ""
}

func (m *CommentItem) GetVideoId() string {
	if m != nil {
		return m.VideoId
	}
	return ""
}

func (m *CommentItem) GetUserItem() *UserItem {
	if m != nil {
		return m.UserItem
	}
	return nil
}

func (m *CommentItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CommentItem) GetReplyCount() uint32 {
	if m != nil {
		return m.ReplyCount
	}
	return 0
}

func (m *CommentItem) GetReplyItems() []*ReplyItem {
	if m != nil {
		return m.ReplyItems
	}
	return nil
}

func (m *CommentItem) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *CommentItem) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func (m *CommentItem) GetCommentTime() uint64 {
	if m != nil {
		return m.CommentTime
	}
	return 0
}

// 回复信息
type ReplyItem struct {
	ReplyId string `protobuf:"bytes,1,opt,name=reply_id,json=replyId" json:"reply_id,omitempty"`
	// Types that are valid to be assigned to Target:
	//	*ReplyItem_CommentItem
	//	*ReplyItem_ReplyItem
	Target    isReplyItem_Target `protobuf_oneof:"Target"`
	UserItem  *UserItem          `protobuf:"bytes,4,opt,name=user_item,json=userItem" json:"user_item,omitempty"`
	Content   string             `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	LikeCount uint32             `protobuf:"varint,6,opt,name=like_count,json=likeCount" json:"like_count,omitempty"`
	Liked     bool               `protobuf:"varint,7,opt,name=liked" json:"liked,omitempty"`
	ReplyTime uint64             `protobuf:"varint,8,opt,name=reply_time,json=replyTime" json:"reply_time,omitempty"`
}

func (m *ReplyItem) Reset()                    { *m = ReplyItem{} }
func (m *ReplyItem) String() string            { return proto.CompactTextString(m) }
func (*ReplyItem) ProtoMessage()               {}
func (*ReplyItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isReplyItem_Target interface {
	isReplyItem_Target()
}

type ReplyItem_CommentItem struct {
	CommentItem *CommentItem `protobuf:"bytes,2,opt,name=comment_item,json=commentItem,oneof"`
}
type ReplyItem_ReplyItem struct {
	ReplyItem *ReplyItem `protobuf:"bytes,3,opt,name=reply_item,json=replyItem,oneof"`
}

func (*ReplyItem_CommentItem) isReplyItem_Target() {}
func (*ReplyItem_ReplyItem) isReplyItem_Target()   {}

func (m *ReplyItem) GetTarget() isReplyItem_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ReplyItem) GetReplyId() string {
	if m != nil {
		return m.ReplyId
	}
	return ""
}

func (m *ReplyItem) GetCommentItem() *CommentItem {
	if x, ok := m.GetTarget().(*ReplyItem_CommentItem); ok {
		return x.CommentItem
	}
	return nil
}

func (m *ReplyItem) GetReplyItem() *ReplyItem {
	if x, ok := m.GetTarget().(*ReplyItem_ReplyItem); ok {
		return x.ReplyItem
	}
	return nil
}

func (m *ReplyItem) GetUserItem() *UserItem {
	if m != nil {
		return m.UserItem
	}
	return nil
}

func (m *ReplyItem) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReplyItem) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *ReplyItem) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func (m *ReplyItem) GetReplyTime() uint64 {
	if m != nil {
		return m.ReplyTime
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ReplyItem) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ReplyItem_OneofMarshaler, _ReplyItem_OneofUnmarshaler, _ReplyItem_OneofSizer, []interface{}{
		(*ReplyItem_CommentItem)(nil),
		(*ReplyItem_ReplyItem)(nil),
	}
}

func _ReplyItem_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ReplyItem)
	// Target
	switch x := m.Target.(type) {
	case *ReplyItem_CommentItem:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CommentItem); err != nil {
			return err
		}
	case *ReplyItem_ReplyItem:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplyItem); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ReplyItem.Target has unexpected type %T", x)
	}
	return nil
}

func _ReplyItem_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ReplyItem)
	switch tag {
	case 2: // Target.comment_item
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CommentItem)
		err := b.DecodeMessage(msg)
		m.Target = &ReplyItem_CommentItem{msg}
		return true, err
	case 3: // Target.reply_item
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplyItem)
		err := b.DecodeMessage(msg)
		m.Target = &ReplyItem_ReplyItem{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ReplyItem_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ReplyItem)
	// Target
	switch x := m.Target.(type) {
	case *ReplyItem_CommentItem:
		s := proto.Size(x.CommentItem)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ReplyItem_ReplyItem:
		s := proto.Size(x.ReplyItem)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 文章信息
type ArticleItem struct {
	LikeCount    uint32         `protobuf:"varint,1,opt,name=like_count,json=likeCount" json:"like_count,omitempty"`
	Liked        bool           `protobuf:"varint,2,opt,name=liked" json:"liked,omitempty"`
	CommentCount uint32         `protobuf:"varint,3,opt,name=comment_count,json=commentCount" json:"comment_count,omitempty"`
	CommentItems []*CommentItem `protobuf:"bytes,4,rep,name=comment_items,json=commentItems" json:"comment_items,omitempty"`
	ViewCount    uint32         `protobuf:"varint,5,opt,name=view_count,json=viewCount" json:"view_count,omitempty"`
	ShareCount   uint32         `protobuf:"varint,6,opt,name=share_count,json=shareCount" json:"share_count,omitempty"`
	ChannelId    string         `protobuf:"bytes,7,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
}

func (m *ArticleItem) Reset()                    { *m = ArticleItem{} }
func (m *ArticleItem) String() string            { return proto.CompactTextString(m) }
func (*ArticleItem) ProtoMessage()               {}
func (*ArticleItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ArticleItem) GetLikeCount() uint32 {
	if m != nil {
		return m.LikeCount
	}
	return 0
}

func (m *ArticleItem) GetLiked() bool {
	if m != nil {
		return m.Liked
	}
	return false
}

func (m *ArticleItem) GetCommentCount() uint32 {
	if m != nil {
		return m.CommentCount
	}
	return 0
}

func (m *ArticleItem) GetCommentItems() []*CommentItem {
	if m != nil {
		return m.CommentItems
	}
	return nil
}

func (m *ArticleItem) GetViewCount() uint32 {
	if m != nil {
		return m.ViewCount
	}
	return 0
}

func (m *ArticleItem) GetShareCount() uint32 {
	if m != nil {
		return m.ShareCount
	}
	return 0
}

func (m *ArticleItem) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

// 推荐信息
type RecommendItem struct {
	Reason  string `protobuf:"bytes,1,opt,name=reason" json:"reason,omitempty"`
	Payload string `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId" json:"trace_id,omitempty"`
}

func (m *RecommendItem) Reset()                    { *m = RecommendItem{} }
func (m *RecommendItem) String() string            { return proto.CompactTextString(m) }
func (*RecommendItem) ProtoMessage()               {}
func (*RecommendItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *RecommendItem) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *RecommendItem) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *RecommendItem) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

// 开关信息
type SwitchItem struct {
	CommentDisabled     bool                      `protobuf:"varint,1,opt,name=comment_disabled,json=commentDisabled" json:"comment_disabled,omitempty"`
	LikeDisabled        bool                      `protobuf:"varint,2,opt,name=like_disabled,json=likeDisabled" json:"like_disabled,omitempty"`
	ShareDisabled       bool                      `protobuf:"varint,3,opt,name=share_disabled,json=shareDisabled" json:"share_disabled,omitempty"`
	ListVideoRatio      float32                   `protobuf:"fixed32,4,opt,name=list_video_ratio,json=listVideoRatio" json:"list_video_ratio,omitempty"`
	DetailVideoMaxRatio float32                   `protobuf:"fixed32,5,opt,name=detail_video_max_ratio,json=detailVideoMaxRatio" json:"detail_video_max_ratio,omitempty"`
	DetailVideoMinRatio float32                   `protobuf:"fixed32,6,opt,name=detail_video_min_ratio,json=detailVideoMinRatio" json:"detail_video_min_ratio,omitempty"`
	FullscreenType      SwitchItem_FullscreenType `protobuf:"varint,7,opt,name=fullscreen_type,json=fullscreenType,enum=budao.SwitchItem_FullscreenType" json:"fullscreen_type,omitempty"`
}

func (m *SwitchItem) Reset()                    { *m = SwitchItem{} }
func (m *SwitchItem) String() string            { return proto.CompactTextString(m) }
func (*SwitchItem) ProtoMessage()               {}
func (*SwitchItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SwitchItem) GetCommentDisabled() bool {
	if m != nil {
		return m.CommentDisabled
	}
	return false
}

func (m *SwitchItem) GetLikeDisabled() bool {
	if m != nil {
		return m.LikeDisabled
	}
	return false
}

func (m *SwitchItem) GetShareDisabled() bool {
	if m != nil {
		return m.ShareDisabled
	}
	return false
}

func (m *SwitchItem) GetListVideoRatio() float32 {
	if m != nil {
		return m.ListVideoRatio
	}
	return 0
}

func (m *SwitchItem) GetDetailVideoMaxRatio() float32 {
	if m != nil {
		return m.DetailVideoMaxRatio
	}
	return 0
}

func (m *SwitchItem) GetDetailVideoMinRatio() float32 {
	if m != nil {
		return m.DetailVideoMinRatio
	}
	return 0
}

func (m *SwitchItem) GetFullscreenType() SwitchItem_FullscreenType {
	if m != nil {
		return m.FullscreenType
	}
	return SwitchItem_PORTRAIT
}

// 视频列表数据信息
type ListItem struct {
	VideoItem     *VideoItem     `protobuf:"bytes,1,opt,name=video_item,json=videoItem" json:"video_item,omitempty"`
	ArticleItem   *ArticleItem   `protobuf:"bytes,2,opt,name=article_item,json=articleItem" json:"article_item,omitempty"`
	TopicItem     *TopicItem     `protobuf:"bytes,3,opt,name=topic_item,json=topicItem" json:"topic_item,omitempty"`
	RecommendItem *RecommendItem `protobuf:"bytes,4,opt,name=recommend_item,json=recommendItem" json:"recommend_item,omitempty"`
	SwitchItem    *SwitchItem    `protobuf:"bytes,5,opt,name=switch_item,json=switchItem" json:"switch_item,omitempty"`
	QuestionItem  *QuestionItem  `protobuf:"bytes,6,opt,name=question_item,json=questionItem" json:"question_item,omitempty"`
}

func (m *ListItem) Reset()                    { *m = ListItem{} }
func (m *ListItem) String() string            { return proto.CompactTextString(m) }
func (*ListItem) ProtoMessage()               {}
func (*ListItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *ListItem) GetVideoItem() *VideoItem {
	if m != nil {
		return m.VideoItem
	}
	return nil
}

func (m *ListItem) GetArticleItem() *ArticleItem {
	if m != nil {
		return m.ArticleItem
	}
	return nil
}

func (m *ListItem) GetTopicItem() *TopicItem {
	if m != nil {
		return m.TopicItem
	}
	return nil
}

func (m *ListItem) GetRecommendItem() *RecommendItem {
	if m != nil {
		return m.RecommendItem
	}
	return nil
}

func (m *ListItem) GetSwitchItem() *SwitchItem {
	if m != nil {
		return m.SwitchItem
	}
	return nil
}

func (m *ListItem) GetQuestionItem() *QuestionItem {
	if m != nil {
		return m.QuestionItem
	}
	return nil
}

type ChannelItem struct {
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ChannelItem) Reset()                    { *m = ChannelItem{} }
func (m *ChannelItem) String() string            { return proto.CompactTextString(m) }
func (*ChannelItem) ProtoMessage()               {}
func (*ChannelItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ChannelItem) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *ChannelItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TabItem struct {
	TabId string `protobuf:"bytes,1,opt,name=tab_id,json=tabId" json:"tab_id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *TabItem) Reset()                    { *m = TabItem{} }
func (m *TabItem) String() string            { return proto.CompactTextString(m) }
func (*TabItem) ProtoMessage()               {}
func (*TabItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *TabItem) GetTabId() string {
	if m != nil {
		return m.TabId
	}
	return ""
}

func (m *TabItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceIOSInfo)(nil), "budao.DeviceIOSInfo")
	proto.RegisterType((*DeviceAndroidInfo)(nil), "budao.DeviceAndroidInfo")
	proto.RegisterType((*DeviceInfo)(nil), "budao.DeviceInfo")
	proto.RegisterType((*EnvironmentInfo)(nil), "budao.EnvironmentInfo")
	proto.RegisterType((*Header)(nil), "budao.Header")
	proto.RegisterType((*Status)(nil), "budao.Status")
	proto.RegisterType((*ShareItem)(nil), "budao.ShareItem")
	proto.RegisterType((*TopicItem)(nil), "budao.TopicItem")
	proto.RegisterType((*VideoItem)(nil), "budao.VideoItem")
	proto.RegisterType((*OptionItem)(nil), "budao.OptionItem")
	proto.RegisterType((*QuestionItem)(nil), "budao.QuestionItem")
	proto.RegisterType((*UserItem)(nil), "budao.UserItem")
	proto.RegisterType((*CommentItem)(nil), "budao.CommentItem")
	proto.RegisterType((*ReplyItem)(nil), "budao.ReplyItem")
	proto.RegisterType((*ArticleItem)(nil), "budao.ArticleItem")
	proto.RegisterType((*RecommendItem)(nil), "budao.RecommendItem")
	proto.RegisterType((*SwitchItem)(nil), "budao.SwitchItem")
	proto.RegisterType((*ListItem)(nil), "budao.ListItem")
	proto.RegisterType((*ChannelItem)(nil), "budao.ChannelItem")
	proto.RegisterType((*TabItem)(nil), "budao.TabItem")
	proto.RegisterEnum("budao.Network", Network_name, Network_value)
	proto.RegisterEnum("budao.Direction", Direction_name, Direction_value)
	proto.RegisterEnum("budao.DeviceInfo_Type", DeviceInfo_Type_name, DeviceInfo_Type_value)
	proto.RegisterEnum("budao.Status_Code", Status_Code_name, Status_Code_value)
	proto.RegisterEnum("budao.QuestionItem_Style", QuestionItem_Style_name, QuestionItem_Style_value)
	proto.RegisterEnum("budao.SwitchItem_FullscreenType", SwitchItem_FullscreenType_name, SwitchItem_FullscreenType_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1934 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x6e, 0x23, 0x49,
	0x15, 0x8e, 0xff, 0xdd, 0xc7, 0xb1, 0xd3, 0xd3, 0x1b, 0x82, 0x67, 0x66, 0x67, 0x67, 0xe8, 0x15,
	0x90, 0x5d, 0x20, 0xa3, 0xcd, 0xcc, 0x6a, 0x90, 0xb8, 0xc1, 0x89, 0x7b, 0x93, 0x66, 0x32, 0x76,
	0xb6, 0xec, 0xcc, 0x22, 0x84, 0x64, 0xb5, 0xdd, 0x95, 0xb8, 0x98, 0x76, 0xb7, 0xb7, 0xbb, 0x9d,
	0x1f, 0xee, 0x78, 0x04, 0xae, 0xb8, 0xe2, 0x06, 0x89, 0x1b, 0x5e, 0x00, 0x24, 0xc4, 0x1b, 0x20,
	0xde, 0x83, 0x67, 0xe0, 0x82, 0x55, 0x9d, 0x53, 0xd5, 0xdd, 0x4e, 0x32, 0x2b, 0xed, 0x5d, 0x9d,
	0xaf, 0xeb, 0x9c, 0x3a, 0xf5, 0x9d, 0xbf, 0xb2, 0x61, 0x73, 0x16, 0x2d, 0x16, 0x51, 0xb8, 0xb7,
	0x8c, 0xa3, 0x34, 0xb2, 0x6a, 0xd3, 0x95, 0xef, 0x45, 0xf6, 0x6b, 0x68, 0xf7, 0xf9, 0xa5, 0x98,
	0x71, 0x77, 0x38, 0x72, 0xc3, 0xf3, 0xc8, 0xb2, 0xa0, 0x2a, 0xfc, 0xf3, 0xcb, 0x6e, 0xe9, 0x59,
	0x69, 0xd7, 0x60, 0xb8, 0x56, 0x98, 0xd7, 0x2d, 0x67, 0x98, 0x27, 0xb1, 0x8b, 0x95, 0xf0, 0xbb,
	0x15, 0xc2, 0xe4, 0xda, 0x0e, 0xe1, 0x01, 0x19, 0xeb, 0x85, 0x7e, 0x1c, 0x09, 0x1f, 0x0d, 0x3e,
	0x01, 0xf0, 0x48, 0x9c, 0x08, 0x5f, 0x99, 0x35, 0x14, 0xe2, 0xfa, 0x68, 0x7b, 0xc1, 0x45, 0x66,
	0x7b, 0xc1, 0x05, 0x61, 0x89, 0xd0, 0xb6, 0xe5, 0x3a, 0x3b, 0xaf, 0x5a, 0x38, 0xef, 0x6f, 0x65,
	0x00, 0xe5, 0xbd, 0x3c, 0xe9, 0x31, 0x18, 0x3e, 0x4a, 0xf9, 0x41, 0x4d, 0x02, 0x5c, 0xdf, 0x7a,
	0x0a, 0x2d, 0x6f, 0xb9, 0x9c, 0x5c, 0xf2, 0x38, 0x11, 0x51, 0xa8, 0x8e, 0x03, 0x6f, 0xb9, 0x7c,
	0x4b, 0x88, 0xf5, 0x0a, 0x5a, 0x4a, 0x3b, 0xbd, 0x59, 0x72, 0x3c, 0xbb, 0xb3, 0xbf, 0xb3, 0x87,
	0x34, 0xed, 0xe5, 0xa7, 0xec, 0x8d, 0x6f, 0x96, 0x9c, 0x01, 0x6d, 0x95, 0x6b, 0x79, 0xc1, 0x28,
	0xc9, 0x0c, 0x93, 0x7f, 0x46, 0x94, 0x68, 0xbb, 0xbb, 0x50, 0x11, 0x51, 0xd2, 0xad, 0x3d, 0x2b,
	0xed, 0xb6, 0xf6, 0xb7, 0xd7, 0xed, 0x11, 0xe7, 0xc7, 0x1b, 0x4c, 0x6e, 0xb1, 0x5e, 0x42, 0x43,
	0xf1, 0xd2, 0xad, 0xe3, 0xee, 0xee, 0xda, 0xee, 0x02, 0xa9, 0xc7, 0x1b, 0x4c, 0x6f, 0xb5, 0x3f,
	0x84, 0x2a, 0xba, 0xd1, 0x82, 0x46, 0x6f, 0xd0, 0x67, 0x43, 0xb7, 0x6f, 0x6e, 0x58, 0x0d, 0xa8,
	0xb8, 0xc3, 0x91, 0x59, 0x3a, 0x68, 0x42, 0x9d, 0xb4, 0xed, 0x3f, 0x95, 0x60, 0xcb, 0x09, 0x2f,
	0x45, 0x1c, 0x85, 0x0b, 0x1e, 0xa6, 0xc8, 0xd8, 0x2e, 0x34, 0x42, 0x9e, 0x5e, 0x45, 0xf1, 0x3b,
	0xe4, 0xab, 0xb3, 0xdf, 0x51, 0x27, 0x0e, 0x08, 0x65, 0xfa, 0xb3, 0xa4, 0x2f, 0xf0, 0x56, 0xe1,
	0x6c, 0x4e, 0xec, 0x28, 0xfa, 0x08, 0xc2, 0xe3, 0x3f, 0x86, 0x36, 0xbf, 0x5e, 0xf2, 0x58, 0x48,
	0xe3, 0x13, 0x95, 0x18, 0x6d, 0xb6, 0x99, 0x83, 0xae, 0x6f, 0x6d, 0x43, 0x2d, 0x49, 0xa3, 0x98,
	0x2b, 0x96, 0x48, 0xb0, 0xff, 0x5d, 0x82, 0xfa, 0x31, 0xf7, 0x7c, 0x1e, 0x5b, 0xdf, 0x87, 0xc6,
	0x2a, 0xe1, 0x71, 0x1e, 0xc0, 0xba, 0x14, 0x49, 0x33, 0x8d, 0xde, 0x71, 0x1d, 0x38, 0x12, 0xac,
	0xfd, 0x2c, 0x66, 0x22, 0x3c, 0x8f, 0xf0, 0xc8, 0xd6, 0xfe, 0x83, 0x3b, 0x31, 0xd3, 0xe1, 0xc2,
	0x3b, 0xf7, 0xc0, 0xe4, 0x39, 0x0d, 0xa4, 0x58, 0x45, 0x45, 0x1d, 0xec, 0x5b, 0x2c, 0xb1, 0x2d,
	0x7e, 0x8b, 0xb6, 0x0f, 0xc1, 0x48, 0xc5, 0x82, 0x27, 0xa9, 0xb7, 0x58, 0x62, 0x60, 0xab, 0x2c,
	0x07, 0xec, 0xbf, 0x96, 0xa1, 0x3e, 0x4a, 0xbd, 0x74, 0x95, 0x58, 0x3f, 0x82, 0xea, 0x2c, 0xf2,
	0xb9, 0x22, 0xd7, 0x52, 0xf6, 0xe9, 0xe3, 0xde, 0x61, 0xe4, 0x73, 0x86, 0xdf, 0xad, 0x2e, 0x34,
	0x16, 0x3c, 0x49, 0xbc, 0x0b, 0xcd, 0xac, 0x16, 0x25, 0xef, 0x09, 0x8f, 0x2f, 0x79, 0x3c, 0x91,
	0x07, 0xe0, 0x0d, 0xab, 0x0c, 0x08, 0x1a, 0x8b, 0x05, 0xb7, 0xff, 0x5e, 0x82, 0xaa, 0xb4, 0x64,
	0xd5, 0xa1, 0x3c, 0x7c, 0x6d, 0x6e, 0x58, 0x1d, 0x80, 0x91, 0xc3, 0xde, 0x3a, 0x6c, 0xe2, 0x30,
	0x66, 0x96, 0xac, 0x2d, 0x68, 0x1d, 0xf4, 0xfa, 0x13, 0xe6, 0x7c, 0x79, 0xe6, 0x8c, 0xc6, 0x66,
	0xd9, 0x7a, 0x00, 0xed, 0xb3, 0x91, 0xc3, 0x26, 0x83, 0xe1, 0xf8, 0x64, 0x78, 0xe4, 0x0e, 0x4c,
	0x99, 0xc2, 0x0f, 0xc7, 0xc3, 0x53, 0xf7, 0x70, 0xc2, 0x9c, 0x53, 0xa7, 0x37, 0x76, 0xfa, 0x93,
	0xd1, 0xd9, 0xc1, 0xe8, 0x90, 0xb9, 0x07, 0x4e, 0xdf, 0x3c, 0xb7, 0x3e, 0x82, 0x47, 0xa8, 0xec,
	0x0e, 0x07, 0xf9, 0x8e, 0xde, 0x60, 0xf4, 0x95, 0xc3, 0x9c, 0xbe, 0x79, 0x61, 0x75, 0x61, 0xfb,
	0xad, 0xdb, 0x77, 0x86, 0xf9, 0xc7, 0x13, 0xf7, 0xb5, 0xd3, 0x37, 0xe7, 0xd6, 0x23, 0xd8, 0x39,
	0x1c, 0xbe, 0x79, 0xe3, 0x0c, 0xc6, 0xb7, 0xbf, 0x09, 0xfb, 0x0f, 0x25, 0x30, 0x46, 0x73, 0x2f,
	0xe6, 0x6e, 0xca, 0x17, 0x18, 0x60, 0x91, 0x06, 0x5c, 0xc5, 0x9d, 0x04, 0x59, 0xf5, 0x3e, 0x4f,
	0x66, 0xba, 0x3b, 0xc8, 0xb5, 0xf5, 0x10, 0x9a, 0x62, 0x16, 0x85, 0x93, 0x55, 0x1c, 0xa8, 0x0e,
	0xd1, 0x90, 0xf2, 0x59, 0x1c, 0xc8, 0x0e, 0x90, 0x48, 0x8b, 0xf8, 0x8d, 0x72, 0xac, 0x89, 0x80,
	0xfc, 0x68, 0x41, 0x35, 0xe5, 0xd7, 0x29, 0x06, 0xcc, 0x60, 0xb8, 0xb6, 0xff, 0x55, 0x06, 0x63,
	0x1c, 0x2d, 0xc5, 0x0c, 0x7d, 0x78, 0x08, 0xcd, 0x54, 0x0a, 0x79, 0xfa, 0x35, 0x50, 0xa6, 0x36,
	0x15, 0x7a, 0x0b, 0x1d, 0x1e, 0x5c, 0x7f, 0x9b, 0x23, 0xda, 0xef, 0x6a, 0xc1, 0xef, 0x8f, 0x00,
	0x92, 0xd5, 0x34, 0x99, 0xc5, 0x62, 0xca, 0x7d, 0xf4, 0xa2, 0xc9, 0x0a, 0x88, 0xf5, 0x63, 0xd8,
	0xca, 0xa4, 0xc9, 0x2c, 0x5a, 0x85, 0x29, 0xb6, 0x81, 0x36, 0xeb, 0x64, 0xf0, 0xa1, 0x44, 0xad,
	0xcf, 0xa0, 0x75, 0x29, 0x7c, 0x1e, 0x4d, 0x44, 0xca, 0x17, 0x49, 0xb7, 0xf1, 0xac, 0xb2, 0xdb,
	0xda, 0x37, 0x55, 0x72, 0xbd, 0x95, 0x5f, 0xe4, 0x6d, 0x18, 0x5c, 0xea, 0x65, 0x62, 0x3d, 0x07,
	0x20, 0x62, 0xa4, 0x4a, 0xb7, 0x89, 0xe9, 0xae, 0x35, 0xb2, 0x18, 0x30, 0x22, 0x0f, 0xa9, 0xf8,
	0x21, 0x74, 0x48, 0xc1, 0x17, 0x89, 0x37, 0x0d, 0xb8, 0xdf, 0x35, 0xd0, 0xe1, 0x36, 0xa2, 0x7d,
	0x05, 0xda, 0xff, 0x2b, 0x81, 0x91, 0x9d, 0x28, 0x09, 0x51, 0x8e, 0x65, 0xfc, 0x91, 0x0f, 0xd8,
	0x7e, 0x97, 0x62, 0x96, 0xae, 0x54, 0x6c, 0x54, 0xff, 0x50, 0x90, 0x64, 0x2c, 0x8b, 0x7f, 0xa5,
	0x18, 0xff, 0x6d, 0xa8, 0x5d, 0x09, 0x3f, 0x9d, 0x23, 0x91, 0x6d, 0x46, 0x82, 0xb5, 0x03, 0xf5,
	0x39, 0x17, 0x17, 0x73, 0x8a, 0x65, 0x9b, 0x29, 0xc9, 0x7a, 0x04, 0x4d, 0x7f, 0x15, 0x7b, 0xa9,
	0xec, 0xc3, 0x44, 0x5d, 0x26, 0x5b, 0x3f, 0x80, 0xcd, 0xe5, 0x6a, 0x1a, 0x88, 0x64, 0x4e, 0x95,
	0xd4, 0xc0, 0x4a, 0x6a, 0x29, 0x4c, 0x96, 0xd2, 0x77, 0x26, 0xc9, 0xfe, 0x73, 0x09, 0x60, 0xb8,
	0x94, 0xe6, 0xf1, 0xfa, 0x8f, 0xc1, 0x88, 0x50, 0x2a, 0xcc, 0x1f, 0x02, 0x88, 0x80, 0xaf, 0x57,
	0x3c, 0xd1, 0x9f, 0x15, 0x01, 0x1a, 0x72, 0x7d, 0xd9, 0x03, 0x66, 0x51, 0x98, 0xf2, 0x30, 0xd5,
	0xc9, 0xa4, 0x44, 0x49, 0x42, 0x8c, 0xb7, 0xad, 0x62, 0x08, 0x48, 0x90, 0x17, 0x9a, 0xcd, 0xa3,
	0x28, 0xd1, 0xb9, 0x42, 0x54, 0xb4, 0x08, 0xc3, 0x44, 0xb1, 0xff, 0x5b, 0x86, 0xcd, 0x2f, 0xf5,
	0x09, 0xd2, 0xc3, 0x5b, 0x4e, 0x94, 0xee, 0x38, 0x51, 0x8c, 0x60, 0x79, 0x3d, 0x82, 0x4f, 0x00,
	0xe6, 0x5e, 0xec, 0x4f, 0x02, 0x7e, 0xc9, 0x03, 0xd5, 0xdd, 0x0d, 0x89, 0x9c, 0x48, 0x00, 0x5b,
	0xfb, 0x4c, 0xb7, 0xf6, 0x36, 0x23, 0xa1, 0x78, 0xa9, 0xda, 0xfa, 0xa5, 0x7e, 0x02, 0x0d, 0xe2,
	0x26, 0xe9, 0xd6, 0x31, 0x81, 0x75, 0xdb, 0xce, 0x09, 0x65, 0x7a, 0x87, 0xcc, 0x46, 0x2f, 0x4c,
	0xae, 0x78, 0xcc, 0x7d, 0x75, 0xdb, 0x06, 0x9e, 0xd2, 0xd6, 0x28, 0x15, 0xc6, 0x73, 0x39, 0x5e,
	0x6e, 0x02, 0x8e, 0xb1, 0xeb, 0xec, 0x3f, 0x54, 0x16, 0x8b, 0x14, 0xec, 0x8d, 0xe4, 0x06, 0x46,
	0xfb, 0xac, 0x5d, 0x30, 0x15, 0x87, 0x79, 0xe0, 0x0c, 0xf4, 0xb3, 0x43, 0xb8, 0x72, 0xc6, 0xb7,
	0x9f, 0x42, 0x0d, 0x35, 0x2d, 0x80, 0xfa, 0xc8, 0x1d, 0x1c, 0x9d, 0x38, 0xe6, 0x86, 0x5c, 0xf7,
	0x87, 0x67, 0x07, 0x27, 0x8e, 0x59, 0xb2, 0xc7, 0xd0, 0x3c, 0x93, 0xa3, 0x4a, 0xd2, 0xfc, 0xde,
	0x29, 0x76, 0x5f, 0x17, 0x79, 0x0c, 0xc6, 0x72, 0x1e, 0xa5, 0x51, 0xa1, 0x8d, 0x34, 0x11, 0x38,
	0x8b, 0x03, 0xfb, 0x9f, 0x65, 0x68, 0x1d, 0x46, 0x0b, 0x9c, 0x3c, 0xd2, 0xf2, 0x13, 0x80, 0x19,
	0x89, 0x85, 0xc7, 0x94, 0x42, 0xbe, 0x3d, 0x7c, 0x3f, 0x05, 0x83, 0x7c, 0x92, 0xb9, 0x4d, 0x83,
	0x72, 0x4b, 0xf1, 0xa3, 0xfd, 0x66, 0xcd, 0x95, 0xbe, 0x41, 0x21, 0x6e, 0xd5, 0xf5, 0xb8, 0x3d,
	0x85, 0x56, 0xcc, 0x97, 0xc1, 0xcd, 0x5a, 0xd6, 0x01, 0x42, 0x59, 0x77, 0xa2, 0x0d, 0xd4, 0x9d,
	0xea, 0x6b, 0xdd, 0x89, 0xc9, 0x2f, 0xd4, 0x9d, 0x62, 0xbd, 0x4c, 0xe4, 0xad, 0x02, 0xf1, 0x8e,
	0xaf, 0x85, 0xd6, 0x90, 0x08, 0x59, 0xdc, 0x86, 0x9a, 0x14, 0x7c, 0x0c, 0x6b, 0x93, 0x91, 0x80,
	0xf9, 0xaf, 0xa8, 0xc0, 0x82, 0x36, 0xa8, 0xa0, 0x15, 0x86, 0xb3, 0xf1, 0x1f, 0x65, 0x30, 0xb2,
	0x13, 0x25, 0x39, 0xca, 0xb1, 0xac, 0x3b, 0x91, 0x0f, 0xbe, 0xf5, 0x2a, 0xb7, 0x85, 0xfc, 0x94,
	0x91, 0x1f, 0x3d, 0xaf, 0x0b, 0x01, 0x38, 0xde, 0xc8, 0x4e, 0x40, 0x9b, 0x9f, 0x01, 0xe4, 0x97,
	0x55, 0xb4, 0xde, 0xb9, 0xeb, 0xf1, 0x06, 0x33, 0xb2, 0xdb, 0xae, 0x07, 0xa2, 0xfa, 0x1d, 0x02,
	0x71, 0xab, 0x80, 0xd6, 0x49, 0xab, 0xbf, 0x97, 0xb4, 0x46, 0x91, 0xb4, 0x27, 0xda, 0x5f, 0xa4,
	0xac, 0x49, 0x4f, 0x17, 0x44, 0x24, 0x61, 0xf2, 0xb5, 0x38, 0xf6, 0xe2, 0x0b, 0x9e, 0xda, 0xff,
	0x2f, 0x41, 0xab, 0x17, 0xa7, 0x62, 0x16, 0x70, 0x9d, 0x78, 0x85, 0xd3, 0x4a, 0xef, 0x3d, 0xad,
	0x5c, 0x3c, 0xed, 0x63, 0x68, 0x6b, 0x5a, 0x49, 0x4f, 0xbd, 0x09, 0x15, 0x48, 0xaa, 0xaf, 0xf2,
	0x4d, 0x94, 0x31, 0x55, 0xcc, 0x98, 0x7b, 0xc8, 0xcf, 0x14, 0xb3, 0xac, 0xb9, 0x14, 0xfc, 0x6a,
	0x2d, 0x11, 0x0d, 0x89, 0x90, 0x5d, 0xf9, 0x72, 0xc2, 0x6e, 0x5e, 0x24, 0x88, 0x1a, 0x3c, 0x6d,
	0x90, 0xb5, 0x34, 0xf7, 0xc2, 0x90, 0x07, 0x32, 0x23, 0x1a, 0xaa, 0x96, 0x08, 0x71, 0x7d, 0xfb,
	0xb7, 0xd0, 0x66, 0x9c, 0x0e, 0xf4, 0x91, 0x82, 0x1d, 0xa8, 0xc7, 0xdc, 0x4b, 0xa2, 0x50, 0x17,
	0x35, 0x49, 0x32, 0x44, 0x4b, 0xef, 0x26, 0x88, 0xbc, 0xac, 0xe6, 0x94, 0x88, 0xef, 0x89, 0xd8,
	0xa3, 0xdf, 0x23, 0xaa, 0xa7, 0xa3, 0xec, 0xfa, 0xf6, 0x1f, 0x2b, 0x00, 0xa3, 0x2b, 0x91, 0xce,
	0xe6, 0x68, 0xfb, 0x13, 0x30, 0x35, 0x09, 0xd9, 0xc0, 0x2d, 0x21, 0x95, 0x5b, 0x0a, 0xd7, 0x23,
	0x57, 0x92, 0x8a, 0x91, 0xc8, 0xf6, 0x11, 0xe5, 0x9b, 0x12, 0xcc, 0x36, 0xdd, 0x1d, 0xdf, 0x95,
	0x7b, 0xc6, 0xb7, 0xec, 0x7f, 0x81, 0x48, 0xd2, 0x09, 0x35, 0x0d, 0x9c, 0x94, 0x98, 0x92, 0x65,
	0xd6, 0x91, 0x38, 0x4e, 0x76, 0x26, 0x51, 0xeb, 0x05, 0xec, 0xf8, 0x3c, 0xf5, 0x44, 0xa0, 0xf6,
	0x2e, 0xbc, 0x6b, 0xb5, 0xbf, 0x86, 0xfb, 0x3f, 0xa0, 0xaf, 0xa8, 0xf1, 0xc6, 0xbb, 0x7e, 0x8f,
	0x92, 0x08, 0x95, 0x52, 0xfd, 0xae, 0x92, 0x08, 0x49, 0xc9, 0x85, 0xad, 0xf3, 0x55, 0x10, 0x24,
	0xb3, 0x98, 0xf3, 0x90, 0x7e, 0x6d, 0x34, 0xb0, 0x9d, 0x3f, 0xd3, 0xa3, 0x38, 0xa3, 0x6d, 0xef,
	0x8b, 0x6c, 0x23, 0xfe, 0x2a, 0xeb, 0x9c, 0xaf, 0xc9, 0xf6, 0xcf, 0xa0, 0xb3, 0xbe, 0xc3, 0xda,
	0x84, 0xe6, 0xe9, 0x90, 0x8d, 0x59, 0xcf, 0x1d, 0x9b, 0x1b, 0x56, 0x1b, 0x8c, 0x93, 0xde, 0xa0,
	0x3f, 0x3a, 0xec, 0x9d, 0xca, 0x16, 0xfe, 0x9f, 0x32, 0x34, 0x4f, 0x44, 0x42, 0x95, 0xfd, 0x1c,
	0x20, 0x7f, 0x64, 0x61, 0x2c, 0xee, 0x7b, 0x63, 0x19, 0xd9, 0x1b, 0xcb, 0xfa, 0x1c, 0x36, 0x3d,
	0x2a, 0x98, 0xfb, 0x7a, 0x48, 0xa1, 0x96, 0x58, 0xcb, 0x2b, 0x14, 0xd6, 0x73, 0x00, 0xf5, 0xe6,
	0xbc, 0xdb, 0x41, 0xb2, 0x97, 0x29, 0x33, 0xd2, 0xec, 0x91, 0xfa, 0x0b, 0xe8, 0xc4, 0x3a, 0x2f,
	0x8b, 0x4d, 0x64, 0x3b, 0x6b, 0x3b, 0x85, 0xa4, 0x65, 0xed, 0x78, 0x2d, 0x87, 0xf7, 0xa1, 0x95,
	0x20, 0x7d, 0xa4, 0x59, 0x5b, 0xfb, 0xc1, 0x94, 0x13, 0xcb, 0x20, 0xc9, 0x73, 0xf3, 0xe7, 0xd0,
	0xce, 0x1f, 0x0d, 0x52, 0x8b, 0x7e, 0x9c, 0x7e, 0x70, 0xcf, 0x74, 0x65, 0x9b, 0x5f, 0x17, 0x24,
	0xfb, 0x97, 0xd0, 0x3a, 0x54, 0xf5, 0xa4, 0x87, 0x57, 0x5e, 0x70, 0xa5, 0x5b, 0x05, 0x77, 0xdf,
	0x70, 0xb4, 0x5f, 0x42, 0x63, 0xec, 0x4d, 0x51, 0xfb, 0x7b, 0x50, 0x4f, 0xbd, 0x69, 0xae, 0x59,
	0x4b, 0xbd, 0xe9, 0xfd, 0x5a, 0x9f, 0x0e, 0xa0, 0xa1, 0x7e, 0xc0, 0xca, 0x11, 0x3d, 0x70, 0xc6,
	0x93, 0xfd, 0x23, 0x1a, 0xd7, 0x72, 0xfd, 0xe2, 0xc8, 0x2c, 0xe9, 0xf5, 0xcb, 0x23, 0xb3, 0xac,
	0xd7, 0x9f, 0x1f, 0x99, 0x15, 0xab, 0x09, 0xd5, 0xaf, 0xdc, 0x2f, 0x5c, 0xb3, 0x6a, 0x19, 0x50,
	0x1b, 0x8e, 0x8f, 0x1d, 0x66, 0xd6, 0x3e, 0xfd, 0x04, 0x8c, 0xbe, 0x88, 0xf9, 0x0c, 0x1f, 0x92,
	0x0d, 0xa8, 0xf4, 0x4e, 0x4e, 0xe8, 0x37, 0xf6, 0x78, 0x78, 0x4a, 0xb6, 0x0e, 0x86, 0xe3, 0xf1,
	0xf0, 0x8d, 0x59, 0x3e, 0x78, 0x84, 0x85, 0xbc, 0xf7, 0xbb, 0xeb, 0xdf, 0xef, 0x2d, 0xa7, 0xc4,
	0xd0, 0x69, 0xe9, 0x2f, 0xe5, 0xca, 0xaf, 0x7e, 0xfd, 0x9b, 0x69, 0x1d, 0xff, 0x79, 0x79, 0xf1,
	0x4d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x7f, 0x10, 0x21, 0x89, 0x11, 0x00, 0x00,
}
